dist: bionic
language: cpp
compiler: gcc

python:
  - "3.7"      # current default Python on Travis CI
git:
  depth: 1
branches:
  only:
    - master
    - staging
addons:
  apt:
    update: true
    sources:
    packages:
      - g++
      - libhwloc-plugins
      - openmpi-bin
      - libopenmpi-dev
      - libboost-all-dev
      - lcov
      - zlib1g-dev
      - libzip-dev
      - libbz2-dev
      - lzma
      - liblzma-dev
      - libtbb-dev
      - libopenmpi-dev
      - vc-dev
      - libzstd-dev
      - xz-utils
      - libunwind-dev
      - libarmadillo-dev
      - libeigen3-dev
      - libpython3.7-dev
      - python3.7-dev
      - wget
      - libsqlite3-dev
install:
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-8 90
script:
  - export PYTHON_EXECUTABLE=`which python3`
  - export PYTHON_INCLUDE_DIR=$(python3 -c "from distutils.sysconfig import get_python_inc; print(get_python_inc())")
  - export PYTHON_LIBRARY=$(python3 -c "import distutils.sysconfig as sysconfig; print(sysconfig.get_config_var('LIBDIR'))")
  - wget https://github.com/VcDevel/Vc/releases/download/1.4.1/Vc-1.4.1.tar.gz
  - tar xf Vc-1.4.1.tar.gz
  - mkdir Vc_build
  - cd Vc_build
  - cmake -DBUILD_EXAMPLES=OFF -DBUILD_TESTING=OFF -DCMAKE_INSTALL_PREFIX=/usr/ -DUSE_LIBMVEC=OFF ../Vc-1.4.1/ 
  - make
  - sudo make install
  - cd ..
  - wget https://github.com/rdkit/rdkit/archive/Release_2019_09_2.tar.gz
  - tar xf Release_2019_09_2.tar.gz
  - mkdir rdkit_build
  - mkdir rdkit_install
  - cd rdkit_build
  - |
    cmake -DCMAKE_INSTALL_PREFIX=../rdkit_install \
    -DRDK_INSTALL_INTREE=OFF \
    -DBUILD_TESTING=OFF \
    -DCMAKE_BUILD_TYPE=Release \
    -DRDK_BUILD_AVALON_SUPPORT=ON \
    -DRDK_BUILD_CAIRO_SUPPORT=OFF \
    -DRDK_BUILD_COMPRESSED_SUPPLIERS=ON \
    -DRDK_BUILD_CONTRIB=ON \
    -DRDK_BUILD_COORDGEN_SUPPORT=ON \
    -DRDK_BUILD_CPP_TESTS=OFF \
    -DRDK_BUILD_DESCRIPTORS3D=ON \
    -DRDK_BUILD_FREESASA_SUPPORT=ON \
    -DRDK_BUILD_INCHI_SUPPORT=OFF \
    -DRDK_BUILD_MINIMAL_LIB=OFF \
    -DRDK_BUILD_MOLINTERCHANGE_SUPPORT=ON \
    -DRDK_BUILD_PGSQL=OFF \
    -DRDK_BUILD_PYTHON_WRAPPERS=OFF \
    -DRDK_BUILD_QT_DEMO=OFF \
    -DRDK_BUILD_QT_SUPPORT=OFF \
    -DRDK_BUILD_RPATH_SUPPORT=OFF \
    -DRDK_BUILD_SLN_SUPPORT=ON \
    -DRDK_BUILD_SWIG_CSHARP_WRAPPER=OFF    \
    -DRDK_BUILD_SWIG_JAVA_WRAPPER=OFF      \
    -DRDK_BUILD_SWIG_WRAPPERS=OFF          \
    -DRDK_BUILD_TEST_GZIP=OFF              \
    -DRDK_BUILD_THREADSAFE_SSS=ON          \
    -DRDK_BUILD_YAEHMOP_SUPPORT=OFF         \
    -DRDK_INSTALL_DEV_COMPONENT=ON         \
    -DRDK_INSTALL_DLLS_MSVC=OFF            \
    -DRDK_INSTALL_PYTHON_TESTS=OFF         \
    -DRDK_INSTALL_STATIC_LIBS=OFF          \
    -DRDK_OPTIMIZE_NATIVE=ON               \
    -DRDK_PGSQL_STATIC=OFF                 \
    -DRDK_SWIG_STATIC=OFF                  \
    -DRDK_TEST_COVERAGE=OFF                \
    -DRDK_TEST_MMFF_COMPLIANCE=OFF         \
    -DRDK_TEST_MULTITHREADED=OFF           \
    -DRDK_USE_BOOST_IOSTREAMS=ON           \
    -DRDK_USE_BOOST_REGEX=ON               \
    -DRDK_USE_BOOST_SERIALIZATION=ON       \
    -DRDK_USE_FLEXBISON=OFF                \
    -DRDK_USE_STRICT_ROTOR_DEFINITION=ON    \
    -DRDK_USE_URF=ON  \
    ../rdkit-Release_2019_09_2/
  - make
  - make install
  - cd ..
  - export LD_LIBRARY_PATH=`pwd`/rdkit_install/lib/:$LD_LIBRARY_PATH
  - mkdir build
  - cd build
  - cmake -DRDKIT_ROOT=`pwd`/../rdkit_install ..
  - make
  - ctest --verbose
  - cd ..
  - sleep 10
after_success:
  - export LD_LIBRARY_PATH=`pwd`/rdkit_install/lib/:$LD_LIBRARY_PATH
  - chmod +x ./runCoverage.sh
  - ./runCoverage.sh -t 1 -s 1 -l 0
  - sleep 10
