//
// Created by eliane on 29/12/18.
//

#include "PDBResiduePropertiesTable.h"


namespace SmolDock {


    // PDB has specific, IUPAC compliant atom name for atoms in proteinogenic amino acid
    // eg : ATOM      5  CB  LEU A 353      12.418  28.143  21.455  1.00 27.35           C
    //                   ^^
    // Here, we use these name to assign the relevant AtomVariant flags, and the partial charge
    // It is basically how far the atom is to the backbone (A : alpha, B : beta, D,G,E,Z,H)
    // Search IUPAC amino acid nomenclature on the web to get nice drawings of which is which
    // The partial charges come from GROMACS implementation of Amber99ff
    // (Findable for example here : https://github.com/gromacs/gromacs/blob/master/share/top/amber99.ff/aminoacids.rtp)

    std::map<AminoAcid::AAType, std::map<std::string, std::tuple<Atom::AtomVariant, double> > > ResidueAtomPropertiesLookupTable_General = {
            {AminoAcid::AAType::alanine,       {{"CA", { Atom::AtomVariant::none,0.033700}},
                                                       {"C", { Atom::AtomVariant::none, 0.597300}},
                                                       {"N", { Atom::AtomVariant::hydrogenDonor, -0.415700}},
                                                       {"O", { Atom::AtomVariant::hydrogenAcceptor, -0.567900}},
                                                       {"OXT", { Atom::AtomVariant::hydrogenAcceptor, -0.805500}},
                                                       {"CB", { Atom::AtomVariant::apolar, -0.182500}}}},
            {AminoAcid::AAType::arginine,      {{"CA", { Atom::AtomVariant::none, -0.263700}},
                                                       {"C", { Atom::AtomVariant::none, 0.734100}},
                                                       {"N", { Atom::AtomVariant::hydrogenDonor, -0.347900}},
                                                       {"O", { Atom::AtomVariant::hydrogenAcceptor, -0.589400}},
                                                       {"OXT", { Atom::AtomVariant::hydrogenAcceptor, -0.826600}},
                                                       {"CB", { Atom::AtomVariant::apolar, -0.000700}},
                                                       {"CG", {  Atom::AtomVariant::apolar, 0.039000}},
                                                       {"CD", {  Atom::AtomVariant::none, 0.048600}},
                                                       {"NE", {  Atom::AtomVariant::hydrogenDonor, 0.345600}},
                                                       {"CZ", {  Atom::AtomVariant::none, 0.807600}},
                                                       {"NH1", { Atom::AtomVariant::hydrogenDonor, -0.862700}},
                                                       {"NH2", { Atom::AtomVariant::hydrogenDonor, -0.862700}}}},
            {AminoAcid::AAType::asparagine,    {{"CA", { Atom::AtomVariant::none, 0.01430}},
                                                       {"C", { Atom::AtomVariant::none, 0.59730}},
                                                       {"N", { Atom::AtomVariant::hydrogenDonor, -0.41570}},
                                                       {"O", { Atom::AtomVariant::hydrogenAcceptor, -0.56790}},
                                                       {"OXT", { Atom::AtomVariant::hydrogenAcceptor, -0.81470 }},
                                                       {"CB", { Atom::AtomVariant::apolar, -0.20410}},
                                                       {"CG", {  Atom::AtomVariant::none, 0.71300}},
                                                       {"OD1", { Atom::AtomVariant::hydrogenAcceptor, -0.59310}},
                                                       {"ND2", { Atom::AtomVariant::hydrogenDonor,-0.91910}}}},
            {AminoAcid::AAType::aspartate,     {{"CA", { Atom::AtomVariant::none, 0.03810}},
                                                       {"C", { Atom::AtomVariant::none, 0.53660}},
                                                       {"N", { Atom::AtomVariant::hydrogenDonor, -0.51630}},
                                                       {"O", { Atom::AtomVariant::hydrogenAcceptor, -0.58190}},
                                                       {"OXT", { Atom::AtomVariant::hydrogenAcceptor, -0.78870}},
                                                       {"CB", { Atom::AtomVariant::apolar, -0.03030}},
                                                       {"CG", {  Atom::AtomVariant::none, 0.79940}},
                                                       {"OD1", { Atom::AtomVariant::hydrogenAcceptor, -0.80140}},
                                                       {"OD2", { Atom::AtomVariant::hydrogenAcceptor, -0.80140}}}},
            {AminoAcid::AAType::cysteine,      {{"CA", { Atom::AtomVariant::none, 0.02130}},
                                                       {"C", { Atom::AtomVariant::none, 0.59730}},
                                                       {"N", { Atom::AtomVariant::hydrogenDonor, -0.41570}},
                                                       {"O", { Atom::AtomVariant::hydrogenAcceptor, -0.56790}},
                                                       {"OXT", { Atom::AtomVariant::hydrogenAcceptor, -0.79810}},
                                                       {"CB", { Atom::AtomVariant::none, -0.12310}},
                                                       // TODO : add a post process step for SG donor status
                                                       {"SG", {  Atom::AtomVariant::hydrogenAcceptor, -0.31190}}}},
            {AminoAcid::AAType::glutamate,     {{"CA", { Atom::AtomVariant::none, 0.03970}},
                                                       {"C", { Atom::AtomVariant::none, 0.53660}},
                                                       {"N", { Atom::AtomVariant::hydrogenDonor, -0.51630}},
                                                       {"O", { Atom::AtomVariant::hydrogenAcceptor, -0.58190}},
                                                       {"OXT", { Atom::AtomVariant::hydrogenAcceptor, -0.79300}},
                                                       {"CB", { Atom::AtomVariant::apolar, 0.05600}},
                                                       {"CG", {  Atom::AtomVariant::apolar, 0.01360}},
                                                       {"CD", {  Atom::AtomVariant::none, 0.80540}},
                                                       {"OE1", { Atom::AtomVariant::hydrogenAcceptor, -0.81880}},
                                                       {"OE2", { Atom::AtomVariant::hydrogenAcceptor, -0.81880}}}},
            {AminoAcid::AAType::glutamine,     {{"CA", { Atom::AtomVariant::none, -0.00310}},
                                                       {"C", { Atom::AtomVariant::none, 0.59730}},
                                                       {"N", { Atom::AtomVariant::hydrogenDonor, -0.41570}},
                                                       {"O", { Atom::AtomVariant::hydrogenAcceptor, -0.56790}},
                                                       {"OXT", { Atom::AtomVariant::hydrogenAcceptor, -0.80420}},
                                                       {"CB", { Atom::AtomVariant::apolar, -0.00360}},
                                                       {"CG", {  Atom::AtomVariant::apolar, -0.06450}},
                                                       {"CD", {  Atom::AtomVariant::none, 0.69510}},
                                                       {"OE1", { Atom::AtomVariant::hydrogenAcceptor, -0.60860}},
                                                       {"NE2", { Atom::AtomVariant::hydrogenDonor, -0.94070}}}},
            {AminoAcid::AAType::glycine,       {{"CA", { Atom::AtomVariant::none, -0.02520}},
                                                       {"C", { Atom::AtomVariant::none, 0.59730}},
                                                       {"N", { Atom::AtomVariant::hydrogenDonor, -0.41570}},
                                                       {"O", { Atom::AtomVariant::hydrogenAcceptor, -0.56790}},
                                                       {"OXT", { Atom::AtomVariant::hydrogenAcceptor,-0.7855}}}},
            {AminoAcid::AAType::histidine,     {{"CA", { Atom::AtomVariant::none, 0.01880}},
                                                       {"C", { Atom::AtomVariant::none, 0.59730}},
                                                       {"N", { Atom::AtomVariant::hydrogenDonor, -0.41570}},
                                                       {"O", { Atom::AtomVariant::hydrogenAcceptor, -0.56790}},
                                                       {"OXT", { Atom::AtomVariant::hydrogenAcceptor, -0.80160}},
                                                       {"CB", { Atom::AtomVariant::apolar, -0.04620}},
                                                       {"CG", {  Atom::AtomVariant::none, -0.02660}},
                                                       {"ND1", { Atom::AtomVariant::hydrogenDonor |
                                                               Atom::AtomVariant::hydrogenAcceptor, -0.38110}},
                                                       {"CD2", { Atom::AtomVariant::none, 0.12920}},
                                                       {"CE1", { Atom::AtomVariant::none, 0.20570}},
                                                       {"NE2", { Atom::AtomVariant::hydrogenDonor |
                                                               Atom::AtomVariant::hydrogenAcceptor, -0.57270}}}},
            {AminoAcid::AAType::isoleucine,    {{"CA", { Atom::AtomVariant::none, -0.05970}},
                                                       {"C", { Atom::AtomVariant::none, 0.59730}},
                                                       {"N", { Atom::AtomVariant::hydrogenDonor,-0.41570}},
                                                       {"O", { Atom::AtomVariant::hydrogenAcceptor, -0.56790}},
                                                       {"OXT", { Atom::AtomVariant::hydrogenAcceptor, -0.81900}},
                                                       {"CB", { Atom::AtomVariant::apolar, 0.13030}},
                                                       {"CG1", { Atom::AtomVariant::apolar, -0.04300}},
                                                       {"CG2", { Atom::AtomVariant::apolar, -0.32040}},
                                                       {"CD1", { Atom::AtomVariant::apolar, -0.06600}}}},
            {AminoAcid::AAType::leucine,       {{"CA", { Atom::AtomVariant::none, -0.05180}},
                                                       {"C", { Atom::AtomVariant::none, 0.59730}},
                                                       {"N", { Atom::AtomVariant::hydrogenDonor, -0.41570}},
                                                       {"O", { Atom::AtomVariant::hydrogenAcceptor, -0.56790}},
                                                       {"OXT", { Atom::AtomVariant::hydrogenAcceptor, -0.81990}},
                                                       {"CB", { Atom::AtomVariant::apolar, -0.11020}},
                                                       {"CG", {  Atom::AtomVariant::apolar, 0.35310}},
                                                       {"CD1", { Atom::AtomVariant::apolar, -0.41210}},
                                                       {"CD2", { Atom::AtomVariant::apolar, -0.41210}}}},
            {AminoAcid::AAType::lysine,        {{"CA", { Atom::AtomVariant::none, -0.24000}},
                                                       {"C", { Atom::AtomVariant::none, 0.73410}},
                                                       {"N", { Atom::AtomVariant::hydrogenDonor,-0.34790}},
                                                       {"O", { Atom::AtomVariant::hydrogenAcceptor, -0.58940}},
                                                       {"OXT", { Atom::AtomVariant::hydrogenAcceptor, -0.82520}},
                                                       {"CB", { Atom::AtomVariant::apolar,  -0.00940}},
                                                       {"CG", {  Atom::AtomVariant::apolar, 0.01870}},
                                                       {"CD", {  Atom::AtomVariant::apolar, -0.04790}},
                                                       {"CE", {  Atom::AtomVariant::none, -0.01430}},
                                                       {"NZ", {  Atom::AtomVariant::hydrogenDonor,-0.38540}}}},
            {AminoAcid::AAType::methionine,    {{"CA", { Atom::AtomVariant::none, -0.02370}},
                                                       {"C", { Atom::AtomVariant::none, 0.59730}},
                                                       {"N", { Atom::AtomVariant::hydrogenDonor, -0.41570}},
                                                       {"O", { Atom::AtomVariant::hydrogenAcceptor, -0.41570}},
                                                       {"OXT", { Atom::AtomVariant::hydrogenAcceptor, -0.81050}},
                                                       {"CB", { Atom::AtomVariant::apolar, 0.03420}},
                                                       {"CG", {  Atom::AtomVariant::none, 0.00180}},
                                                       {"SD", {  Atom::AtomVariant::none, -0.27370 }},
                                                       {"CE", {  Atom::AtomVariant::none, -0.05360}}}},
            {AminoAcid::AAType::phenylalanine, {{"CA", { Atom::AtomVariant::none, -0.00240}},
                                                       {"C", { Atom::AtomVariant::none, 0.59730}},
                                                       {"N", { Atom::AtomVariant::hydrogenDonor, -0.41570}},
                                                       {"O", { Atom::AtomVariant::hydrogenAcceptor, -0.56790}},
                                                       {"OXT", { Atom::AtomVariant::hydrogenAcceptor, -0.80260}},
                                                       {"CB", { Atom::AtomVariant::apolar, -0.03430}},
                                                       {"CG", {  Atom::AtomVariant::apolar, 0.01180}},
                                                       {"CD1", { Atom::AtomVariant::apolar, -0.12560}},
                                                       {"CD2", { Atom::AtomVariant::apolar, -0.12560}},
                                                       {"CE1", { Atom::AtomVariant::apolar, -0.17040}},
                                                       {"CE2", { Atom::AtomVariant::apolar, -0.17040}},
                                                       {"CZ", {  Atom::AtomVariant::apolar, -0.10720}}}},
            {AminoAcid::AAType::proline,       {{"CA", { Atom::AtomVariant::none, -0.02660}},
                                                       {"C", { Atom::AtomVariant::none, 0.58960}},
                                                       {"N", { Atom::AtomVariant::none, -0.25480}},
                                                       {"O", { Atom::AtomVariant::hydrogenAcceptor,-0.57480}},
                                                       {"OXT", { Atom::AtomVariant::hydrogenAcceptor, -0.76970}},
                                                       {"CB", { Atom::AtomVariant::apolar, -0.00700}},
                                                       {"CG", {  Atom::AtomVariant::apolar, 0.01890}},
                                                       {"CD", {  Atom::AtomVariant::none, 0.01920}}}},
            {AminoAcid::AAType::serine,        {{"CA", { Atom::AtomVariant::none, -0.02490}},
                                                       {"C", { Atom::AtomVariant::none, 0.59730}},
                                                       {"N", { Atom::AtomVariant::hydrogenDonor, -0.41570}},
                                                       {"O", { Atom::AtomVariant::hydrogenAcceptor, -0.56790}},
                                                       {"OXT", { Atom::AtomVariant::hydrogenAcceptor, -0.81320}},
                                                       {"CB", { Atom::AtomVariant::none, 0.21170}},
                                                       {"OG", {  Atom::AtomVariant::hydrogenDonor |
                                                               Atom::AtomVariant::hydrogenAcceptor, -0.65460}}}},
            {AminoAcid::AAType::threonine,     {{"CA", { Atom::AtomVariant::none, -0.03890}},
                                                       {"C", { Atom::AtomVariant::none, 0.59730}},
                                                       {"N", { Atom::AtomVariant::hydrogenDonor, -0.41570}},
                                                       {"O", { Atom::AtomVariant::hydrogenAcceptor, -0.56790}},
                                                       {"OXT", { Atom::AtomVariant::hydrogenAcceptor, -0.80440}},
                                                       {"CB", { Atom::AtomVariant::none, 0.36540}},
                                                       {"OG1", { Atom::AtomVariant::hydrogenDonor |
                                                               Atom::AtomVariant::hydrogenAcceptor, -0.67610}},
                                                       {"CG2", { Atom::AtomVariant::none, -0.24380}}}},
            {AminoAcid::AAType::tryptophan,    {{"CA", { Atom::AtomVariant::none, -0.02750}},
                                                       {"C", { Atom::AtomVariant::none, 0.59730}},
                                                       {"N", { Atom::AtomVariant::hydrogenDonor, -0.41570}},
                                                       {"O", { Atom::AtomVariant::hydrogenAcceptor,  -0.56790}},
                                                       {"OXT", { Atom::AtomVariant::hydrogenAcceptor, -0.80110}},
                                                       {"CB", { Atom::AtomVariant::apolar, -0.00500}},
                                                       {"CG", {  Atom::AtomVariant::apolar, -0.14150}},
                                                       {"CD1", { Atom::AtomVariant::none, -0.16380}},
                                                       {"CD2", { Atom::AtomVariant::apolar, 0.12430}},
                                                       {"NE1", { Atom::AtomVariant::hydrogenDonor, -0.34180}},
                                                       {"CE2", { Atom::AtomVariant::none, 0.13800}},
                                                       {"CE3", { Atom::AtomVariant::apolar, -0.23870}},
                                                       {"CZ2", { Atom::AtomVariant::apolar, -0.26010}},
                                                       {"CZ3", { Atom::AtomVariant::apolar, -0.19720}},
                                                       {"CH2", { Atom::AtomVariant::apolar, -0.11340}}}},
            {AminoAcid::AAType::tyrosine,      {{"CA", { Atom::AtomVariant::none, -0.00140}},
                                                       {"C", { Atom::AtomVariant::none, 0.59730}},
                                                       {"N", { Atom::AtomVariant::hydrogenDonor, -0.41570}},
                                                       {"O", { Atom::AtomVariant::hydrogenAcceptor, -0.56790}},
                                                       {"OXT", { Atom::AtomVariant::hydrogenAcceptor, -0.80700}},
                                                       {"CB", { Atom::AtomVariant::apolar, -0.01520}},
                                                       {"CG", {  Atom::AtomVariant::apolar, -0.00110}},
                                                       {"CD1", { Atom::AtomVariant::apolar, -0.19060}},
                                                       {"CD2", { Atom::AtomVariant::apolar, -0.19060}},
                                                       {"CE1", { Atom::AtomVariant::apolar, -0.23410}},
                                                       {"CE2", { Atom::AtomVariant::apolar, -0.23410}},
                                                       {"CZ", {  Atom::AtomVariant::none,  0.32260}},
                                                       {"OH", {  Atom::AtomVariant::hydrogenDonor |
                                                               Atom::AtomVariant::hydrogenAcceptor, -0.55790}}}},
            {AminoAcid::AAType::valine,        {{"CA", { Atom::AtomVariant::none, -0.08750}},
                                                       {"C", { Atom::AtomVariant::none, 0.59730}},
                                                       {"N", { Atom::AtomVariant::hydrogenDonor, -0.41570}},
                                                       {"O", { Atom::AtomVariant::hydrogenAcceptor, -0.56790}},
                                                       {"OXT", { Atom::AtomVariant::hydrogenAcceptor, -0.81730}},
                                                       {"CB", { Atom::AtomVariant::apolar, 0.29850}},
                                                       {"CG1", { Atom::AtomVariant::apolar, -0.31920}},
                                                       {"CG2", { Atom::AtomVariant::apolar, -0.31920}},}},
            {AminoAcid::AAType::selenocysteine,
                                               {{"CA", { Atom::AtomVariant::none, 0.02130}},
                                                       {"C", { Atom::AtomVariant::none, 0.59730 }},
                                                       {"N", { Atom::AtomVariant::hydrogenDonor, -0.41570}},
                                                       {"O", { Atom::AtomVariant::hydrogenAcceptor, -0.56790}},
                                                       {"OXT", { Atom::AtomVariant::hydrogenAcceptor, -0.79810}},
                                                       {"CB", { Atom::AtomVariant::none, -0.12310 }},
                                                       {"SEG", { Atom::AtomVariant::none, -0.31190}}}}, // TODO: add apropriatr charges (currently sec=cys)
            {AminoAcid::AAType::pyrrolysine,   {{"CA", { Atom::AtomVariant::none, 0.02130}},
                                                       {"C", { Atom::AtomVariant::none, 0.59730}},
                                                       {"N", { Atom::AtomVariant::hydrogenDonor, -0.41570}},
                                                       {"O", { Atom::AtomVariant::hydrogenAcceptor, -0.5679}},
                                                       {"OXT", { Atom::AtomVariant::hydrogenAcceptor, -0.79810}}}}
    };


}