//
// Created by eliane on 29/12/18.
//

#include "PDBResiduePropertiesTable.h"


namespace SmolDock {


    // PDB has specific, IUPAC compliant atom name for atoms in proteinogenic amino acid
    // eg : ATOM      5  CB  LEU A 353      12.418  28.143  21.455  1.00 27.35           C
    //                   ^^
    // Here, we use these name to assign the relevant AtomVariant flags, and the partial charge
    // It is basically how far the atom is to the backbone (A : alpha, B : beta, D,G,E,Z,H)
    // Search IUPAC amino acid nomenclature on the web to get nice drawings of which is which
    // The partial charges come from Ambertools file amino12.lib
    // (Findable for example here : https://github.com/choderalab/ambermini/blob/master/share/amber/dat/leap/lib/amino12.lib)
    // TODO: figure out the exact licence of the file : possibly GPL or public domain

    std::set<std::tuple<AminoAcid::AAType, std::vector<std::tuple<std::string, Atom::AtomVariant, double> > > > ResidueAtomPropertiesLookupTable_General = {
            {AminoAcid::AAType::alanine,       {{"CA", Atom::AtomVariant::none,0.033700},
                                                       {"C", Atom::AtomVariant::none, 0.597300},
                                                       {"N", Atom::AtomVariant::hydrogenDonor, -0.415700},
                                                       {"O", Atom::AtomVariant::hydrogenAcceptor, -0.567900},
                                                       {"OXT", Atom::AtomVariant::hydrogenAcceptor, -0.805500},
                                                       {"CB", Atom::AtomVariant::apolar, -0.182500}}},
            {AminoAcid::AAType::arginine,      {{"CA", Atom::AtomVariant::none, -0.263700},
                                                       {"C", Atom::AtomVariant::none, 0.734100},
                                                       {"N", Atom::AtomVariant::hydrogenDonor, -0.347900},
                                                       {"O", Atom::AtomVariant::hydrogenAcceptor, -0.589400},
                                                       {"OXT", Atom::AtomVariant::hydrogenAcceptor, -0.826600},
                                                       {"CB", Atom::AtomVariant::apolar, -0.000700},
                                                       {"CG",  Atom::AtomVariant::apolar, 0.039000},
                                                       {"CD",  Atom::AtomVariant::none, 0.048600},
                                                       {"NE",  Atom::AtomVariant::hydrogenDonor, 0.345600},
                                                       {"CZ",  Atom::AtomVariant::none, 0.807600},
                                                       {"NH1", Atom::AtomVariant::hydrogenDonor, -0.862700},
                                                       {"NH2", Atom::AtomVariant::hydrogenDonor, -0.862700}}},
            {AminoAcid::AAType::asparagine,    {{"CA", Atom::AtomVariant::none},
                                                       {"C", Atom::AtomVariant::none},
                                                       {"N", Atom::AtomVariant::hydrogenDonor},
                                                       {"O", Atom::AtomVariant::hydrogenAcceptor},
                                                       {"OXT", Atom::AtomVariant::hydrogenAcceptor},
                                                       {"CB", Atom::AtomVariant::apolar},
                                                       {"CG",  Atom::AtomVariant::none},
                                                       {"OD1", Atom::AtomVariant::hydrogenAcceptor},
                                                       {"ND2", Atom::AtomVariant::hydrogenDonor}}},
            {AminoAcid::AAType::aspartate,     {{"CA", Atom::AtomVariant::none},
                                                       {"C", Atom::AtomVariant::none},
                                                       {"N", Atom::AtomVariant::hydrogenDonor},
                                                       {"O", Atom::AtomVariant::hydrogenAcceptor},
                                                       {"OXT", Atom::AtomVariant::hydrogenAcceptor},
                                                       {"CB", Atom::AtomVariant::apolar},
                                                       {"CG",  Atom::AtomVariant::none},
                                                       {"OD1", Atom::AtomVariant::hydrogenAcceptor},
                                                       {"OD2", Atom::AtomVariant::hydrogenAcceptor}}},
            {AminoAcid::AAType::cysteine,      {{"CA", Atom::AtomVariant::none},
                                                       {"C", Atom::AtomVariant::none},
                                                       {"N", Atom::AtomVariant::hydrogenDonor},
                                                       {"O", Atom::AtomVariant::hydrogenAcceptor},
                                                       {"OXT", Atom::AtomVariant::hydrogenAcceptor},
                                                       {"CB", Atom::AtomVariant::none},
                                                       // TODO : add a post process step for SG donor status
                                                       {"SG",  Atom::AtomVariant::hydrogenAcceptor}}},
            {AminoAcid::AAType::glutamate,     {{"CA", Atom::AtomVariant::none},
                                                       {"C", Atom::AtomVariant::none},
                                                       {"N", Atom::AtomVariant::hydrogenDonor},
                                                       {"O", Atom::AtomVariant::hydrogenAcceptor},
                                                       {"OXT", Atom::AtomVariant::hydrogenAcceptor},
                                                       {"CB", Atom::AtomVariant::apolar},
                                                       {"CG",  Atom::AtomVariant::apolar},
                                                       {"CD",  Atom::AtomVariant::none},
                                                       {"OE1", Atom::AtomVariant::hydrogenAcceptor},
                                                       {"OE2", Atom::AtomVariant::hydrogenAcceptor}}},
            {AminoAcid::AAType::glutamine,     {{"CA", Atom::AtomVariant::none},
                                                       {"C", Atom::AtomVariant::none},
                                                       {"N", Atom::AtomVariant::hydrogenDonor},
                                                       {"O", Atom::AtomVariant::hydrogenAcceptor},
                                                       {"OXT", Atom::AtomVariant::hydrogenAcceptor},
                                                       {"CB", Atom::AtomVariant::apolar},
                                                       {"CG",  Atom::AtomVariant::apolar},
                                                       {"CD",  Atom::AtomVariant::none},
                                                       {"OE1", Atom::AtomVariant::hydrogenAcceptor},
                                                       {"NE2", Atom::AtomVariant::hydrogenDonor}}},
            {AminoAcid::AAType::glycine,       {{"CA", Atom::AtomVariant::none},
                                                       {"C", Atom::AtomVariant::none},
                                                       {"N", Atom::AtomVariant::hydrogenDonor},
                                                       {"O", Atom::AtomVariant::hydrogenAcceptor},
                                                       {"OXT", Atom::AtomVariant::hydrogenAcceptor}}},
            {AminoAcid::AAType::histidine,     {{"CA", Atom::AtomVariant::none},
                                                       {"C", Atom::AtomVariant::none},
                                                       {"N", Atom::AtomVariant::hydrogenDonor},
                                                       {"O", Atom::AtomVariant::hydrogenAcceptor},
                                                       {"OXT", Atom::AtomVariant::hydrogenAcceptor},
                                                       {"CB", Atom::AtomVariant::apolar},
                                                       {"CG",  Atom::AtomVariant::none},
                                                       {"ND1", Atom::AtomVariant::hydrogenDonor |
                                                               Atom::AtomVariant::hydrogenAcceptor},
                                                       {"CD2", Atom::AtomVariant::none},
                                                       {"CE1", Atom::AtomVariant::none},
                                                       {"NE2", Atom::AtomVariant::hydrogenDonor |
                                                               Atom::AtomVariant::hydrogenAcceptor}}},
            {AminoAcid::AAType::isoleucine,    {{"CA", Atom::AtomVariant::none},
                                                       {"C", Atom::AtomVariant::none},
                                                       {"N", Atom::AtomVariant::hydrogenDonor},
                                                       {"O", Atom::AtomVariant::hydrogenAcceptor},
                                                       {"OXT", Atom::AtomVariant::hydrogenAcceptor},
                                                       {"CB", Atom::AtomVariant::apolar},
                                                       {"CG1", Atom::AtomVariant::apolar},
                                                       {"CG2", Atom::AtomVariant::apolar},
                                                       {"CD1", Atom::AtomVariant::apolar}}},
            {AminoAcid::AAType::leucine,       {{"CA", Atom::AtomVariant::none},
                                                       {"C", Atom::AtomVariant::none},
                                                       {"N", Atom::AtomVariant::hydrogenDonor},
                                                       {"O", Atom::AtomVariant::hydrogenAcceptor},
                                                       {"OXT", Atom::AtomVariant::hydrogenAcceptor},
                                                       {"CB", Atom::AtomVariant::apolar},
                                                       {"CG",  Atom::AtomVariant::apolar},
                                                       {"CD1", Atom::AtomVariant::apolar},
                                                       {"CD2", Atom::AtomVariant::apolar}}},
            {AminoAcid::AAType::lysine,        {{"CA", Atom::AtomVariant::none},
                                                       {"C", Atom::AtomVariant::none},
                                                       {"N", Atom::AtomVariant::hydrogenDonor},
                                                       {"O", Atom::AtomVariant::hydrogenAcceptor},
                                                       {"OXT", Atom::AtomVariant::hydrogenAcceptor},
                                                       {"CB", Atom::AtomVariant::apolar},
                                                       {"CG",  Atom::AtomVariant::apolar},
                                                       {"CD",  Atom::AtomVariant::apolar},
                                                       {"CE",  Atom::AtomVariant::none},
                                                       {"NZ",  Atom::AtomVariant::hydrogenDonor}}},
            {AminoAcid::AAType::methionine,    {{"CA", Atom::AtomVariant::none},
                                                       {"C", Atom::AtomVariant::none},
                                                       {"N", Atom::AtomVariant::hydrogenDonor},
                                                       {"O", Atom::AtomVariant::hydrogenAcceptor},
                                                       {"OXT", Atom::AtomVariant::hydrogenAcceptor},
                                                       {"CB", Atom::AtomVariant::apolar},
                                                       {"CG",  Atom::AtomVariant::none},
                                                       {"SD",  Atom::AtomVariant::none},
                                                       {"CE",  Atom::AtomVariant::none}}},
            {AminoAcid::AAType::phenylalanine, {{"CA", Atom::AtomVariant::none},
                                                       {"C", Atom::AtomVariant::none},
                                                       {"N", Atom::AtomVariant::hydrogenDonor},
                                                       {"O", Atom::AtomVariant::hydrogenAcceptor},
                                                       {"OXT", Atom::AtomVariant::hydrogenAcceptor},
                                                       {"CB", Atom::AtomVariant::apolar},
                                                       {"CG",  Atom::AtomVariant::apolar},
                                                       {"CD1", Atom::AtomVariant::apolar},
                                                       {"CD2", Atom::AtomVariant::apolar},
                                                       {"CE1", Atom::AtomVariant::apolar},
                                                       {"CE2", Atom::AtomVariant::apolar},
                                                       {"CZ",  Atom::AtomVariant::apolar}}},
            {AminoAcid::AAType::proline,       {{"CA", Atom::AtomVariant::none},
                                                       {"C", Atom::AtomVariant::none},
                                                       {"N", Atom::AtomVariant::none},
                                                       {"O", Atom::AtomVariant::hydrogenAcceptor},
                                                       {"OXT", Atom::AtomVariant::hydrogenAcceptor},
                                                       {"CB", Atom::AtomVariant::apolar},
                                                       {"CG",  Atom::AtomVariant::apolar},
                                                       {"CD",  Atom::AtomVariant::none}}},
            {AminoAcid::AAType::serine,        {{"CA", Atom::AtomVariant::none},
                                                       {"C", Atom::AtomVariant::none},
                                                       {"N", Atom::AtomVariant::hydrogenDonor},
                                                       {"O", Atom::AtomVariant::hydrogenAcceptor},
                                                       {"OXT", Atom::AtomVariant::hydrogenAcceptor},
                                                       {"CB", Atom::AtomVariant::none},
                                                       {"OG",  Atom::AtomVariant::hydrogenDonor |
                                                               Atom::AtomVariant::hydrogenAcceptor}}},
            {AminoAcid::AAType::threonine,     {{"CA", Atom::AtomVariant::none},
                                                       {"C", Atom::AtomVariant::none},
                                                       {"N", Atom::AtomVariant::hydrogenDonor},
                                                       {"O", Atom::AtomVariant::hydrogenAcceptor},
                                                       {"OXT", Atom::AtomVariant::hydrogenAcceptor},
                                                       {"CB", Atom::AtomVariant::none},
                                                       {"OG1", Atom::AtomVariant::hydrogenDonor |
                                                               Atom::AtomVariant::hydrogenAcceptor},
                                                       {"CG2", Atom::AtomVariant::none}}},
            {AminoAcid::AAType::tryptophan,    {{"CA", Atom::AtomVariant::none},
                                                       {"C", Atom::AtomVariant::none},
                                                       {"N", Atom::AtomVariant::hydrogenDonor},
                                                       {"O", Atom::AtomVariant::hydrogenAcceptor},
                                                       {"OXT", Atom::AtomVariant::hydrogenAcceptor},
                                                       {"CB", Atom::AtomVariant::apolar},
                                                       {"CG",  Atom::AtomVariant::apolar},
                                                       {"CD1", Atom::AtomVariant::none},
                                                       {"CD2", Atom::AtomVariant::apolar},
                                                       {"NE1", Atom::AtomVariant::hydrogenDonor},
                                                       {"CE2", Atom::AtomVariant::none},
                                                       {"CE3", Atom::AtomVariant::apolar},
                                                       {"CZ2", Atom::AtomVariant::apolar},
                                                       {"CZ3", Atom::AtomVariant::apolar},
                                                       {"CH2", Atom::AtomVariant::apolar}}},
            {AminoAcid::AAType::tyrosine,      {{"CA", Atom::AtomVariant::none},
                                                       {"C", Atom::AtomVariant::none},
                                                       {"N", Atom::AtomVariant::hydrogenDonor},
                                                       {"O", Atom::AtomVariant::hydrogenAcceptor},
                                                       {"OXT", Atom::AtomVariant::hydrogenAcceptor},
                                                       {"CB", Atom::AtomVariant::apolar},
                                                       {"CG",  Atom::AtomVariant::apolar},
                                                       {"CD1", Atom::AtomVariant::apolar},
                                                       {"CD2", Atom::AtomVariant::apolar},
                                                       {"CE1", Atom::AtomVariant::apolar},
                                                       {"CE2", Atom::AtomVariant::apolar},
                                                       {"CZ",  Atom::AtomVariant::none},
                                                       {"OH",  Atom::AtomVariant::hydrogenDonor |
                                                               Atom::AtomVariant::hydrogenAcceptor}}},
            {AminoAcid::AAType::valine,        {{"CA", Atom::AtomVariant::none},
                                                       {"C", Atom::AtomVariant::none},
                                                       {"N", Atom::AtomVariant::hydrogenDonor},
                                                       {"O", Atom::AtomVariant::hydrogenAcceptor},
                                                       {"OXT", Atom::AtomVariant::hydrogenAcceptor},
                                                       {"CB", Atom::AtomVariant::apolar},
                                                       {"CG1", Atom::AtomVariant::apolar},
                                                       {"CG2", Atom::AtomVariant::apolar},}},
            {AminoAcid::AAType::selenocysteine,
                                               {{"CA", Atom::AtomVariant::none},
                                                       {"C", Atom::AtomVariant::none},
                                                       {"N", Atom::AtomVariant::hydrogenDonor},
                                                       {"O", Atom::AtomVariant::hydrogenAcceptor},
                                                       {"OXT", Atom::AtomVariant::hydrogenAcceptor},
                                                       {"CB", Atom::AtomVariant::none},
                                                       {"SEG", Atom::AtomVariant::none}}},
            {AminoAcid::AAType::pyrrolysine,   {{"CA", Atom::AtomVariant::none},
                                                       {"C", Atom::AtomVariant::none},
                                                       {"N", Atom::AtomVariant::hydrogenDonor},
                                                       {"O", Atom::AtomVariant::hydrogenAcceptor},
                                                       {"OXT", Atom::AtomVariant::hydrogenAcceptor}}}
    };


}