SmolDock: PyStructures.cpp File Reference
PyStructures.cpp File Reference
#include <boost/python.hpp>
#include <boost/numpy.hpp>
#include <Structures/Molecule.h>
#include <Structures/Protein.h>
#include <Structures/Results/DockingResult.h>
Functions
void export_Structures ()
Function Documentation
export_Structures()
void export_Structures ()
Definition at line 39 of file PyStructures.cpp.
References SmolDock::iProtein::AAId_to_AtomPositionInVect, SmolDock::iProtein::center_x, SmolDock::iProtein::center_y, SmolDock::iProtein::center_z, SmolDock::Molecule::deepcopy(), SmolDock::Molecule::generateConformer(), SmolDock::Molecule::getInitialConformer(), SmolDock::Protein::getiProtein(), SmolDock::Molecule::getResidueName(), SmolDock::DockingResult::ligandPoses, SmolDock::Molecule::numberOfAtoms(), SmolDock::Molecule::numberOfBonds(), SmolDock::Protein::populateFromPDB(), SmolDock::Molecule::populateFromPDB(), SmolDock::Molecule::populateFromSMILES(), SmolDock::Molecule::setResidueName(), SmolDock::iConformer::type, SmolDock::iProtein::type, SmolDock::Molecule::updateAtomPositionsFromiConformer(), SmolDock::iConformer::variant, SmolDock::iProtein::variant, SmolDock::iConformer::x, SmolDock::iProtein::x, SmolDock::iConformer::y, SmolDock::iProtein::y, SmolDock::iConformer::z, and SmolDock::iProtein::z.
 {
     p::class_<sd::Molecule>("Molecule")
             .def("populateFromPDB", &sd::Molecule::populateFromPDB, populateFromPDB_overloads())
             .def("populateFromSMILES", &sd::Molecule::populateFromSMILES, populateFromSMILES_overloads())
             .add_property("numberOfAtoms", &sd::Molecule::numberOfAtoms)
             .add_property("numberOfBonds", &sd::Molecule::numberOfBonds)
             .def("getInitialConformer", &sd::Molecule::getInitialConformer)
             .def("generateConformer", &sd::Molecule::generateConformer, generateConformer_overloads() )
             .add_property("residueName", &sd::Molecule::getResidueName, &sd::Molecule::setResidueName)
             .def("updateAtomPositionsFromiConformer", &sd::Molecule::updateAtomPositionsFromiConformer)
             .def("deepcopy", &sd::Molecule::deepcopy)
             //.def("populateFromPDB", &sd::Molecule::populateFromPDB)
             //.def("set", &World::set)
             //.add_property("rovalue", &Num::get)
             //.add_property("value", &Num::get, &Num::set);
             ;
     p::class_<sd::iConformer>("iConformer")
             .def_readwrite("x", &sd::iConformer::x)
             .def_readwrite("y", &sd::iConformer::y)
             .def_readwrite("z", &sd::iConformer::z)
             .def_readwrite("type", &sd::iConformer::type)
             .def_readwrite("variant", &sd::iConformer::variant)
             ;
     p::class_<sd::iProtein>("iProtein")
             .def_readwrite("center_x", &sd::iProtein::center_x)
             .def_readwrite("center_y", &sd::iProtein::center_y)
             .def_readwrite("center_z", &sd::iProtein::center_z)
             .def_readwrite("x", &sd::iProtein::x)
             .def_readwrite("y", &sd::iProtein::y)
             .def_readwrite("z", &sd::iProtein::z)
             .def_readwrite("type", &sd::iProtein::type)
             .def_readwrite("variant", &sd::iProtein::variant)
             .def_readwrite("AAId_to_AtomPositionInVect", &sd::iProtein::AAId_to_AtomPositionInVect)
             ;
     p::class_<sd::Protein>("Protein")
             .def("populateFromPDB", &sd::Protein::populateFromPDB)
             .def("getiProtein", &sd::Protein::getiProtein)
             ;
     p::class_<sd::DockingResult>("DockingResult")
             .def_readwrite("ligandPoses", &sd::DockingResult::ligandPoses)
             ;
 }