SmolDock: SmolDock::Optimizer::GradientDescentLineSearch Class Reference
SmolDock::Optimizer::GradientDescentLineSearch Class Reference
#include <GradientDescentLineSearch.h>
Public Member Functions
GradientDescentLineSearch (Score::ScoringFunction *scoringFunc_, double differentialUpsilon=1e-3)
bool optimize (arma::mat startingPoint) final
arma::mat getRawResultMatrix () final
double getScore () final
unsigned int getIterationNumber ()
~GradientDescentLineSearch () final=default
Public Member Functions inherited from SmolDock::Optimizer::Optimizer
virtual ~Optimizer ()=default
Private Attributes
Score::ScoringFunction * scoringFunction
double differential_epsilon
unsigned int paramVectorDimension
arma::mat result
unsigned int iterationNumber
double score
Detailed Description
Definition at line 22 of file GradientDescentLineSearch.h.
Constructor & Destructor Documentation
GradientDescentLineSearch()
SmolDock::Optimizer::GradientDescentLineSearch::GradientDescentLineSearch (Score::ScoringFunction * scoringFunc_, double differentialUpsilon = 1e-3) explicit
Definition at line 23 of file GradientDescentLineSearch.cpp.
~GradientDescentLineSearch()
SmolDock::Optimizer::GradientDescentLineSearch::~GradientDescentLineSearch () final default
Member Function Documentation
getIterationNumber()
unsigned int SmolDock::Optimizer::GradientDescentLineSearch::getIterationNumber ()
Definition at line 117 of file GradientDescentLineSearch.cpp.
References iterationNumber.
getRawResultMatrix()
arma::mat SmolDock::Optimizer::GradientDescentLineSearch::getRawResultMatrix () final virtual
Implements SmolDock::Optimizer::Optimizer.
Definition at line 121 of file GradientDescentLineSearch.cpp.
References result.
getScore()
double SmolDock::Optimizer::GradientDescentLineSearch::getScore () final virtual
Implements SmolDock::Optimizer::Optimizer.
Definition at line 125 of file GradientDescentLineSearch.cpp.
References score.
optimize()
bool SmolDock::Optimizer::GradientDescentLineSearch::optimize (arma::mat startingPoint) final virtual
Implements SmolDock::Optimizer::Optimizer.
Definition at line 33 of file GradientDescentLineSearch.cpp.
References differential_epsilon, SmolDock::Score::ScoringFunction::Evaluate(), SmolDock::Score::ScoringFunction::EvaluateWithGradient(), SmolDock::Optimizer::hasNonZeroComponent(), iterationNumber, paramVectorDimension, result, score, and scoringFunction.
Member Data Documentation
differential_epsilon
double SmolDock::Optimizer::GradientDescentLineSearch::differential_epsilon private
Definition at line 39 of file GradientDescentLineSearch.h.
iterationNumber
unsigned int SmolDock::Optimizer::GradientDescentLineSearch::iterationNumber private
Definition at line 43 of file GradientDescentLineSearch.h.
paramVectorDimension
unsigned int SmolDock::Optimizer::GradientDescentLineSearch::paramVectorDimension private
Definition at line 40 of file GradientDescentLineSearch.h.
result
arma::mat SmolDock::Optimizer::GradientDescentLineSearch::result private
Definition at line 41 of file GradientDescentLineSearch.h.
score
double SmolDock::Optimizer::GradientDescentLineSearch::score private
Definition at line 44 of file GradientDescentLineSearch.h.
scoringFunction
Score::ScoringFunction* SmolDock::Optimizer::GradientDescentLineSearch::scoringFunction private
Definition at line 38 of file GradientDescentLineSearch.h.
The documentation for this class was generated from the following files:
GradientDescentLineSearch.h
GradientDescentLineSearch.cpp