SmolDock: SmolDock::Heuristics::SimulatedAnnealing Class Reference
SmolDock::Heuristics::SimulatedAnnealing Class Reference
#include <SimulatedAnnealing.h>
Classes
struct Parameters
Public Member Functions
SimulatedAnnealing (Score::ScoringFunction *scorFunc_, Optimizer::Optimizer *optimizer_, unsigned int seed_, SimulatedAnnealing::Parameters params_)
bool search () final
arma::mat getResultMatrix () final
~SimulatedAnnealing () final=default
Public Member Functions inherited from SmolDock::Heuristics::GlobalHeuristic
virtual ~GlobalHeuristic ()=default
Private Attributes
Score::ScoringFunction * scorFunc
Optimizer::Optimizer * optimizer
std::mt19937 rndGenerator
arma::mat result
Parameters params
Detailed Description
Definition at line 16 of file SimulatedAnnealing.h.
Class Documentation
SmolDock::Heuristics::SimulatedAnnealing::Parameters
struct SmolDock::Heuristics::SimulatedAnnealing::Parameters
Definition at line 29 of file SimulatedAnnealing.h.
Constructor & Destructor Documentation
SimulatedAnnealing()
SmolDock::Heuristics::SimulatedAnnealing::SimulatedAnnealing (Score::ScoringFunction * scorFunc_, Optimizer::Optimizer * optimizer_, unsigned int seed_, SimulatedAnnealing::Parameters params_)
Definition at line 17 of file SimulatedAnnealing.cpp.
~SimulatedAnnealing()
SmolDock::Heuristics::SimulatedAnnealing::~SimulatedAnnealing () final default
Member Function Documentation
getResultMatrix()
arma::mat SmolDock::Heuristics::SimulatedAnnealing::getResultMatrix () final virtual
Implements SmolDock::Heuristics::GlobalHeuristic.
Definition at line 46 of file SimulatedAnnealing.cpp.
References result.
search()
bool SmolDock::Heuristics::SimulatedAnnealing::search () final virtual
Implements SmolDock::Heuristics::GlobalHeuristic.
Definition at line 23 of file SimulatedAnnealing.cpp.
References SmolDock::Score::ScoringFunction::Evaluate(), SmolDock::Optimizer::Optimizer::getRawResultMatrix(), SmolDock::Optimizer::Optimizer::getScore(), SmolDock::Score::ScoringFunction::getStartingConditions(), SmolDock::Optimizer::Optimizer::optimize(), optimizer, result, and scorFunc.
Member Data Documentation
optimizer
Optimizer::Optimizer* SmolDock::Heuristics::SimulatedAnnealing::optimizer private
Definition at line 35 of file SimulatedAnnealing.h.
params
Parameters SmolDock::Heuristics::SimulatedAnnealing::params private
Definition at line 41 of file SimulatedAnnealing.h.
result
arma::mat SmolDock::Heuristics::SimulatedAnnealing::result private
Definition at line 39 of file SimulatedAnnealing.h.
rndGenerator
std::mt19937 SmolDock::Heuristics::SimulatedAnnealing::rndGenerator private
Definition at line 37 of file SimulatedAnnealing.h.
scorFunc
Score::ScoringFunction* SmolDock::Heuristics::SimulatedAnnealing::scorFunc private
Definition at line 34 of file SimulatedAnnealing.h.
The documentation for this class was generated from the following files:
SimulatedAnnealing.h
SimulatedAnnealing.cpp