SmolDock: SmolDock::GradientDescentLineSearch Class Reference
SmolDock::GradientDescentLineSearch Class Reference
#include <GradientDescentLineSearch.h>
Public Member Functions
GradientDescentLineSearch (std::function< double(const iConformer &, const iTransform &, const iProtein &)> scorFunc, double differentialUpsilon=0.01)
void setProtein (const iProtein *prot)
void setStartingConformer (const iConformer *conformer)
bool optimize ()
iConformer getFinalConformer ()
double getScore ()
unsigned int getIterationNumber ()
Private Member Functions
iConformer getCurrentConformerWithTransform ()
Private Attributes
std::function< double(const iConformer &, const iTransform &, const iProtein &)> scoringFunction
const iConformer * startingConformer
iConformer currentConformer
const iProtein * protein
iTransform currentTransform
double score = 0
unsigned int iterationNbr = 0
double differential_epsilon
Detailed Description
Definition at line 20 of file GradientDescentLineSearch.h.
Constructor & Destructor Documentation
GradientDescentLineSearch()
SmolDock::GradientDescentLineSearch::GradientDescentLineSearch (std::function< double(const iConformer &, const iTransform &, const iProtein &)> scorFunc, double differentialUpsilon = 0.01)
Definition at line 20 of file GradientDescentLineSearch.cpp.
                                         :
             scoringFunction(scorFunc),
             differential_epsilon(differentialUpsilon) {
     }
Member Function Documentation
getCurrentConformerWithTransform()
iConformer SmolDock::GradientDescentLineSearch::getCurrentConformerWithTransform () private
Definition at line 231 of file GradientDescentLineSearch.cpp.
References SmolDock::applyTransformInPlace(), currentConformer, and currentTransform.
{
         iConformer current = this->currentConformer;
         applyTransformInPlace(current, this->currentTransform);
         return current;
     }
getFinalConformer()
iConformer SmolDock::GradientDescentLineSearch::getFinalConformer ()
Definition at line 222 of file GradientDescentLineSearch.cpp.
References SmolDock::applyTransformInPlace(), currentConformer, and currentTransform.
{
         applyTransformInPlace(this->currentConformer, this->currentTransform);
         return this->currentConformer;
     }
getIterationNumber()
unsigned int SmolDock::GradientDescentLineSearch::getIterationNumber ()
Definition at line 237 of file GradientDescentLineSearch.cpp.
References iterationNbr.
{
         return this->iterationNbr;
     }
getScore()
double SmolDock::GradientDescentLineSearch::getScore ()
Definition at line 227 of file GradientDescentLineSearch.cpp.
References score.
{
         return this->score;
     }
optimize()
bool SmolDock::GradientDescentLineSearch::optimize ()
Definition at line 28 of file GradientDescentLineSearch.cpp.
References SmolDock::IntermediateConformerCollector::addiConformer(), currentConformer, currentTransform, differential_epsilon, SmolDock::iGradient::ds, SmolDock::iGradient::dt, SmolDock::iGradient::du, SmolDock::iGradient::dv, SmolDock::iGradient::dx, SmolDock::iGradient::dy, SmolDock::iGradient::dz, getCurrentConformerWithTransform(), iterationNbr, SmolDock::iTransformIdentityInit(), SmolDock::normalizeQuaternionInPlace(), protein, SmolDock::iTransform::rota, SmolDock::iQuaternion::s, score, scoringFunction, SmolDock::iQuaternion::t, SmolDock::iTransform::transl, SmolDock::iQuaternion::u, SmolDock::iQuaternion::v, SmolDock::iTranslation::x, SmolDock::iTranslation::y, and SmolDock::iTranslation::z.
{
         this->currentTransform = iTransformIdentityInit();
         iGradient translationGradient;
         double score = this->scoringFunction(this->currentConformer, this->currentTransform, *(this->protein));
         double oldscore;
         double score_progress = 100.0;
         while (score_progress > 0.001) {
             oldscore = score;
             BOOST_LOG_TRIVIAL(info) << "\n";
             BOOST_LOG_TRIVIAL(debug) << "score: " << score;
             // Compute approx gradient to find in which direction to go
             // Translation
             iTransform transform_dx = this->currentTransform;
             transform_dx.transl.x += this->differential_epsilon;
             translationGradient.dx =
                     oldscore - this->scoringFunction(this->currentConformer, transform_dx, *(this->protein));
             iTransform transform_dy = this->currentTransform;
             transform_dy.transl.y += this->differential_epsilon;
             translationGradient.dy =
                     oldscore - this->scoringFunction(this->currentConformer, transform_dy, *(this->protein));
             iTransform transform_dz = this->currentTransform;
             transform_dz.transl.z += this->differential_epsilon;
             translationGradient.dz =
                     oldscore - this->scoringFunction(this->currentConformer, transform_dz, *(this->protein));
             // Rotation
             iTransform transform_ds = this->currentTransform;
             transform_ds.rota.s += this->differential_epsilon;
             normalizeQuaternionInPlace(transform_ds.rota);
             translationGradient.ds =
                     oldscore - this->scoringFunction(this->currentConformer, transform_ds, *(this->protein));
             iTransform transform_du = this->currentTransform;
             transform_du.rota.u += this->differential_epsilon;
             normalizeQuaternionInPlace(transform_du.rota);
             translationGradient.du =
                     oldscore - this->scoringFunction(this->currentConformer, transform_du, *(this->protein));
             iTransform transform_dv = this->currentTransform;
             transform_dv.rota.v += this->differential_epsilon;
             normalizeQuaternionInPlace(transform_dv.rota);
             translationGradient.dv =
                     oldscore - this->scoringFunction(this->currentConformer, transform_dv, *(this->protein));
             iTransform transform_dt = this->currentTransform;
             transform_dt.rota.t += this->differential_epsilon;
             normalizeQuaternionInPlace(transform_dt.rota);
             translationGradient.dt =
                     oldscore - this->scoringFunction(this->currentConformer, transform_dt, *(this->protein));
             BOOST_LOG_TRIVIAL(debug) << "Gradient";
             BOOST_LOG_TRIVIAL(debug) << "     ds: " << translationGradient.ds;
             BOOST_LOG_TRIVIAL(debug) << "     du: " << translationGradient.du << "   dx: " << translationGradient.dx;
             BOOST_LOG_TRIVIAL(debug) << "     dv: " << translationGradient.dv << "   dy: " << translationGradient.dy;
             BOOST_LOG_TRIVIAL(debug) << "     dt: " << translationGradient.dt << "   dx: " << translationGradient.dz;
             // Now we want to know how far in that direction
             // We do a line-search
             iTransform transform_linesearch;
             double step = this->differential_epsilon / 10;
             double previous_step = 0.0;
             double temp_score;
             double previous_temp_score = std::numeric_limits<double>::max();
             // We go further and further in the direction of the gradient, until we are not bettering the score
             while (true) {
                 transform_linesearch = this->currentTransform;
                 transform_linesearch.transl.x += step * translationGradient.dx;
                 transform_linesearch.transl.y += step * translationGradient.dy;
                 transform_linesearch.transl.z += step * translationGradient.dz;
                 transform_linesearch.rota.s += step * translationGradient.ds;
                 transform_linesearch.rota.u += step * translationGradient.du;
                 transform_linesearch.rota.v += step * translationGradient.dv;
                 transform_linesearch.rota.t += step * translationGradient.dt;
                 normalizeQuaternionInPlace(transform_linesearch.rota);
                 temp_score = this->scoringFunction(this->currentConformer, transform_linesearch, *(this->protein));
                 double diff_oldscore_tempscore = oldscore - temp_score;
                 double diff_previous_tempscore = previous_temp_score - temp_score;
                 /*
                 BOOST_LOG_TRIVIAL(info) << "";
                 BOOST_LOG_TRIVIAL(debug) << "oldscore: " << oldscore;
                 BOOST_LOG_TRIVIAL(debug) << "temp_score: " << temp_score;
                 BOOST_LOG_TRIVIAL(debug) << "previous_temp_score: " << previous_temp_score;
                 BOOST_LOG_TRIVIAL(debug) << "diff_oldscore_tempscore: " << diff_oldscore_tempscore;
                 BOOST_LOG_TRIVIAL(debug) << "diff_previous_tempscore: " << diff_previous_tempscore;
 */
                 previous_temp_score = temp_score;
                 if (diff_oldscore_tempscore > 0  // temp_score is lower than the old score thus better
                      && diff_previous_tempscore > 0 ) // It is also lower than in the previous iteration
                 {
                     // so we jump further to see if it can be even better
                     previous_step = step;
                     step = step * 10;
                     BOOST_LOG_TRIVIAL(debug) << "Going further: " << step;
                     continue;
                 } else {
                     BOOST_LOG_TRIVIAL(debug) << "Regression, stepping back to " << previous_step;
                     // We hit a step that is not better than either oldscore or the previous iterator
                     break;
                 }
             }
             // We then go back to previous_step for updating the score
             if (previous_step == 0.0) {
                 // This means we could not do any jump forward
                 // So this is the best we can do (to the precision of the starting step 0.0001 (angstrom))
                 // So we stop the search (this is one of the stop condition, the other is score_progress)
                 break;
             }
             // Otherwise we update the transform and go for another round
             this->currentTransform.transl.x += previous_step * translationGradient.dx;
             this->currentTransform.transl.y += previous_step * translationGradient.dy;
             this->currentTransform.transl.z += previous_step * translationGradient.dz;
             this->currentTransform.rota.s += previous_step * translationGradient.ds;
             this->currentTransform.rota.u += previous_step * translationGradient.du;
             this->currentTransform.rota.v += previous_step * translationGradient.dv;
             this->currentTransform.rota.t += previous_step * translationGradient.dt;
             normalizeQuaternionInPlace(this->currentTransform.rota);
             BOOST_LOG_TRIVIAL(debug) << "== Accepted transform after iteration ==";
             BOOST_LOG_TRIVIAL(debug) << "     s: " << this->currentTransform.rota.s;
             BOOST_LOG_TRIVIAL(debug) << "     u: " << this->currentTransform.rota.u << "   x: " << this->currentTransform.transl.x;
             BOOST_LOG_TRIVIAL(debug) << "     v: " << this->currentTransform.rota.v << "   y: " << this->currentTransform.transl.y;
             BOOST_LOG_TRIVIAL(debug) << "     t: " << this->currentTransform.rota.t << "   x: " << this->currentTransform.transl.z;
             score = this->scoringFunction(this->currentConformer, this->currentTransform, *(this->protein));
             score_progress = oldscore - score;
             this->iterationNbr++;
             conformerCollector->addiConformer(this->getCurrentConformerWithTransform());
             //BOOST_LOG_TRIVIAL(debug) << "     Score: " << score << " (progress: "<< score_progress <<  " )";
         }
         this->score = score;
         /*
         scores.push_back(score);
         final_transform.push_back(transform);
         record_timings(end_docking_this_conformer);
         acc_iteration(iterationNbr);
         acc_score(score);
         acc_duration(
                 static_cast< std::chrono::duration<double> >(end_docking_this_conformer -
                                                              begin_docking_this_conformer).count()
         );
          */
         return true;
     }
setProtein()
void SmolDock::GradientDescentLineSearch::setProtein (const iProtein * prot)
Definition at line 212 of file GradientDescentLineSearch.cpp.
References protein.
{
         this->protein = prot;
     }
setStartingConformer()
void SmolDock::GradientDescentLineSearch::setStartingConformer (const iConformer * conformer)
Definition at line 216 of file GradientDescentLineSearch.cpp.
References SmolDock::IntermediateConformerCollector::addiConformer(), conformerCollector, currentConformer, and startingConformer.
{
         this->startingConformer = conformer;
         conformerCollector->addiConformer(*this->startingConformer);
         this->currentConformer = *conformer;
     }
Member Data Documentation
currentConformer
iConformer SmolDock::GradientDescentLineSearch::currentConformer private
Definition at line 36 of file GradientDescentLineSearch.h.
currentTransform
iTransform SmolDock::GradientDescentLineSearch::currentTransform private
Definition at line 39 of file GradientDescentLineSearch.h.
differential_epsilon
double SmolDock::GradientDescentLineSearch::differential_epsilon private
Definition at line 43 of file GradientDescentLineSearch.h.
iterationNbr
unsigned int SmolDock::GradientDescentLineSearch::iterationNbr = 0 private
Definition at line 41 of file GradientDescentLineSearch.h.
protein
const iProtein* SmolDock::GradientDescentLineSearch::protein private
Definition at line 37 of file GradientDescentLineSearch.h.
score
double SmolDock::GradientDescentLineSearch::score = 0 private
Definition at line 40 of file GradientDescentLineSearch.h.
scoringFunction
std::function<double(const iConformer&, const iTransform&,const iProtein&)> SmolDock::GradientDescentLineSearch::scoringFunction private
Definition at line 34 of file GradientDescentLineSearch.h.
startingConformer
const iConformer* SmolDock::GradientDescentLineSearch::startingConformer private
Definition at line 35 of file GradientDescentLineSearch.h.
The documentation for this class was generated from the following files:
GradientDescentLineSearch.h
GradientDescentLineSearch.cpp