SmolDock: SmolDock::Molecule Class Reference
SmolDock::Molecule Class Reference
Class representing "rich" molecule.
#include <Molecule.h>
Public Member Functions
Molecule ()
bool populateFromSMILES (const std::string &smiles, unsigned int seed=36754)
Populate atoms and bonds from SMILES.
bool populateFromPDB (const std::string &filename, const std::string &smiles_hint="", unsigned int seed=36754)
Populate atoms and bonds from a PDB file. Additionally, a SMILES string can be used for bond order hint.
unsigned int numberOfAtoms ()
Return the number of atom in the Molecule, Hydrogen excepted.
unsigned int numberOfBonds ()
Return the number of bonds in the Molecule.
iConformer getInitialConformer ()
Obtain the conformer that was either loaded from file or generated when populating the Molecule.
bool generateConformer (iConformer &conformer, int seed=367454)
Generate a conformer of this molecule.
unsigned int generateConformers (std::vector< iConformer > &viConformers, unsigned int num, int seed=367454)
Generate a vector of conformer of this molecule.
std::string getResidueName () const
Get the 3-letter residue code used for this molecule in PDB file.
void setResidueName (const std::string &res_name)
Set the 3-letter residue code used for this molecule in PDB file.
bool updateAtomPositionsFromiConformer (const iConformer &conformer)
Molecule deepcopy ()
Make a copy of the Molecule object where the underlying Atom and Bond are new objects instead of references to.
Private Member Functions
bool populateInternalAtomAndBondFromRWMol (unsigned int seed)
Use this if using RDKit RWMol as entry.
Private Attributes
std::vector< std::shared_ptr< Atom > > atoms
std::vector< std::shared_ptr< Bond > > bonds
std::shared_ptr< RDKit::RWMol > rwmol
std::string smiles
std::string residue_name = "LIG"
int initial_conformer_id = -1
Friends
class MoleculeTraversal
class UnitTestHelper
class PDBWriter
Detailed Description
Class representing "rich" molecule.
Contains all extended attributes and functions.
Definition at line 54 of file Molecule.h.
Constructor & Destructor Documentation
Molecule()
SmolDock::Molecule::Molecule () default
Member Function Documentation
deepcopy()
Molecule SmolDock::Molecule::deepcopy ()
Make a copy of the Molecule object where the underlying Atom and Bond are new objects instead of references to.
Returns
A new Molecule object with copied values
Definition at line 336 of file Molecule.cpp.
References atoms, bonds, SmolDock::Atom::bonds, rwmol, and SmolDock::Bond::setBondType().
{
         Molecule newmol(*this);
         std::vector< std::tuple<std::shared_ptr<Atom>,Atom*> > new_old_lookup_table;
         newmol.atoms.clear();
         for(auto& ptr: this->atoms)
         {
             Atom* newatom_ptr = new Atom(*ptr);
             newatom_ptr->bonds.clear(); // We will restore it after rebuilding the bonds
             std::shared_ptr<Atom>& inserted = newmol.atoms.emplace_back(newatom_ptr);
             new_old_lookup_table.push_back(std::make_tuple(inserted,ptr.get())); // Register new/old pair to rebuild bonds
         }
         newmol.bonds.clear();
         for(auto& ptr: this->bonds)
         {
             Atom* endA_ptr = ptr->getEndA().get();
             Atom* endB_ptr = ptr->getEndB().get();
             // Find matches in lookup table :
             std::shared_ptr<Atom> endA = std::get<0>(*(std::find_if(std::begin(new_old_lookup_table), std::end(new_old_lookup_table),
                                    [&](const std::tuple<std::shared_ptr<Atom>,Atom*> &e) {
                                        return (std::get<1>(e) == endA_ptr);
                                    })));
             std::shared_ptr<Atom> endB = std::get<0>(*(std::find_if(std::begin(new_old_lookup_table), std::end(new_old_lookup_table),
                                                                     [&](const std::tuple<std::shared_ptr<Atom>,Atom*> &e) {
                                                                         return (std::get<1>(e) == endB_ptr);
                                                                     })));
             Bond* newbond = new Bond(endA,endB,ptr->getBondID());
             newbond->setBondType(ptr->getBondType());
             std::shared_ptr<Bond>& inserted_bond = newmol.bonds.emplace_back(newbond);
             // PublicizeToAtom uses enable_shared_from_this, which means the previous statement, creating a shared_ptr
             // must occur before the following statement, lest throw std::bad_weak_ptr
             inserted_bond->publicizeToAtom();
         }
         newmol.rwmol.reset(new RDKit::RWMol(*rwmol));
         return newmol;
     }
generateConformer()
bool SmolDock::Molecule::generateConformer (iConformer & conformer, int seed = 367454)
Generate a conformer of this molecule.
Parameters
conformer Reference to conformer object to be filled. Not modified if generation fails.
seed RNG seed
Returns
Returns true if successfully generated conformer, false otherwise
See also
generateConformers()
Definition at line 70 of file Molecule.cpp.
References SmolDock::iConformer::atomicRadius, atoms, SmolDock::atomTypeToAtomicRadius(), rwmol, SmolDock::stringToAtomType(), SmolDock::iConformer::type, SmolDock::iConformer::x, SmolDock::iConformer::y, and SmolDock::iConformer::z.
{
         // Hydrogen added for conformer gen
         RDKit::MolOps::addHs(*rwmol);
         int conformer_id = RDKit::DGeomHelpers::EmbedMolecule(*rwmol, 10, seed, false);
         RDKit::MolOps::removeHs(*rwmol);
         if (conformer_id == -1) // Failed to generate
             return false;
         conformer.x.reserve(static_cast<size_t>(this->atoms.size()));
         conformer.y.reserve(static_cast<size_t>(this->atoms.size()));
         conformer.z.reserve(static_cast<size_t>(this->atoms.size()));
         conformer.type.reserve(static_cast<size_t>(this->atoms.size()));
         RDKit::Conformer &rdkit_conformer = rwmol->getConformer(conformer_id);
         for (auto atom_it = rwmol->beginAtoms(); atom_it != rwmol->endAtoms(); ++atom_it) {
             assert((*atom_it)->getAtomicNum() != 1); // Conformer should not contain Hs (which were removed earlier)
             conformer.type.push_back(static_cast<unsigned char>((*atom_it)->getAtomicNum()));
             const RDGeom::Point3D &position = rdkit_conformer.getAtomPos((*atom_it)->getIdx());
             conformer.x.push_back(position.x);
             conformer.y.push_back(position.y);
             conformer.z.push_back(position.z);
             // FIXME : this means there is an encapsulation problem, likely due to the RWMol* being in Molecule but not linked to Atom
             conformer.atomicRadius.push_back(atomTypeToAtomicRadius(
                     stringToAtomType(boost::to_upper_copy<std::string>((*atom_it)->getSymbol()))));
         }
         return true;
     }
generateConformers()
unsigned int SmolDock::Molecule::generateConformers (std::vector< iConformer > & viConformers, unsigned int num, int seed = 367454)
Generate a vector of conformer of this molecule.
Parameters
viConformers Pointer to vector to be filled with conformer. May already contain something.
num Number of conformers to attempt to generate.
seed RNG seed
Returns
Returns the number of conformer actually generated. May be 0.
See also
generateConformer()
Definition at line 107 of file Molecule.cpp.
References SmolDock::iConformer::atomicRadius, atoms, SmolDock::atomTypeToAtomicRadius(), initial_conformer_id, rwmol, SmolDock::stringToAtomType(), SmolDock::iConformer::type, SmolDock::iConformer::variant, SmolDock::iConformer::x, SmolDock::iConformer::y, and SmolDock::iConformer::z.
{
         std::vector<int> conformer_ids = RDKit::DGeomHelpers::EmbedMultipleConfs(*rwmol, // Molecule
                                                                                  num, // Num of conformer
                                                                                  30, // Max attempts
                                                                                  seed, // RNG seed
                                                                                  false); // Erase existing conformer
         if (conformer_ids.size() == 0)
             return 0; // Early failure case
         viConformers.reserve(viConformers.capacity() + conformer_ids.size() + 1);
         // Add the initial conformer
         conformer_ids.push_back(this->initial_conformer_id);
         unsigned int num_atoms = this->atoms.size();
         for (int i : conformer_ids) {
             iConformer conformer;
             RDKit::Conformer rdkit_conformer = this->rwmol->getConformer(i);
             conformer.x.reserve(static_cast<size_t>(num_atoms));
             conformer.y.reserve(static_cast<size_t>(num_atoms));
             conformer.z.reserve(static_cast<size_t>(num_atoms));
             conformer.type.reserve(static_cast<size_t>(num_atoms));
             for (auto atom_it = rwmol->beginAtoms(); atom_it != rwmol->endAtoms(); ++atom_it) {
                 conformer.type.push_back(static_cast<unsigned char>((*atom_it)->getAtomicNum()));
                 conformer.variant.push_back(0); // Not implemented
                 const RDGeom::Point3D &position = rdkit_conformer.getAtomPos((*atom_it)->getIdx());
                 conformer.x.push_back(position.x);
                 conformer.y.push_back(position.y);
                 conformer.z.push_back(position.z);
                 // FIXME : this means there is an encapsulation problem, likely due to the RWMol* being in Molecule but not linked to Atom
                 conformer.atomicRadius.push_back(atomTypeToAtomicRadius(
                         stringToAtomType(boost::to_upper_copy<std::string>((*atom_it)->getSymbol()))));
             }
             viConformers.push_back(std::move(conformer));
         }
         return conformer_ids.size();
     }
getInitialConformer()
iConformer SmolDock::Molecule::getInitialConformer ()
Obtain the conformer that was either loaded from file or generated when populating the Molecule.
If the Molecule was loaded from a file format containing coordinate (PDB, ...), the initial conformer has those coordinate. Otherwise, it is a RDKit generated conformer.
Returns
Returns iConformer for initial conformer
See also
generateConformer(), generateConformers()
Definition at line 381 of file Molecule.cpp.
References SmolDock::iConformer::atomicRadius, SmolDock::atomTypeToAtomicRadius(), rwmol, SmolDock::stringToAtomType(), SmolDock::iConformer::type, SmolDock::iConformer::x, SmolDock::iConformer::y, and SmolDock::iConformer::z.
{
         iConformer conformer;
         auto rdkit_conformer = (*(this->rwmol->beginConformers()));
         for (auto atom_it = this->rwmol->beginAtoms(); atom_it != this->rwmol->endAtoms(); ++atom_it) {
             assert((*atom_it)->getAtomicNum() != 1); // Conformer should not contain Hs (which were removed earlier)
             conformer.type.push_back(static_cast<unsigned char>((*atom_it)->getAtomicNum()));
             const RDGeom::Point3D &position = rdkit_conformer->getAtomPos((*atom_it)->getIdx());
             conformer.x.push_back(position.x);
             conformer.y.push_back(position.y);
             conformer.z.push_back(position.z);
             conformer.atomicRadius.push_back(atomTypeToAtomicRadius(
                     stringToAtomType(boost::to_upper_copy<std::string>((*atom_it)->getSymbol()))));
         }
         return conformer;
     }
getResidueName()
std::string SmolDock::Molecule::getResidueName () const
Get the 3-letter residue code used for this molecule in PDB file.
Returns
A 3-letter residue name string
See also
setResidueName()
Definition at line 184 of file Molecule.cpp.
References residue_name.
{
         return this->residue_name;
     }
numberOfAtoms()
unsigned int SmolDock::Molecule::numberOfAtoms ()
Return the number of atom in the Molecule, Hydrogen excepted.
Definition at line 155 of file Molecule.cpp.
References atoms.
{
         return atoms.size();
     }
numberOfBonds()
unsigned int SmolDock::Molecule::numberOfBonds ()
Return the number of bonds in the Molecule.
Definition at line 159 of file Molecule.cpp.
References bonds.
{
         return bonds.size();
     }
populateFromPDB()
bool SmolDock::Molecule::populateFromPDB (const std::string & filename, const std::string & smiles_hint = "", unsigned int seed = 36754)
Populate atoms and bonds from a PDB file. Additionally, a SMILES string can be used for bond order hint.
Due to limitation of the PDB file format, it is difficult to infer bond order (single/double/aromatic bond) from connectivity data. The underlying implementation in RDKit does not attempts it. A SMILES string with the correct aromaticity/bonds can be supplied to help obtain accurate internal representation.
Only the first model and first chain of the PDB file is used to construct the molecule.
Populate atoms and bonds from SMILES. This uses the RDKit backend.
Parameters
filename Path to PDB file
smiles_hint SMILES for the loaded molecule. If none available, use the empty string.
Returns
whether the parsing and initial conformer generation was successful.
See also
populateFromSMILES()
Definition at line 163 of file Molecule.cpp.
References SmolDock::AssignBondOrderFromTemplateSMILES(), populateInternalAtomAndBondFromRWMol(), and rwmol.
{
         // Flavor = 1 --> ignore alternate location
         RDKit::RWMol *mol = RDKit::PDBFileToMol(filename, false, false, 1, true);
         if (mol == nullptr) {
             return false;
         }
         this->rwmol.reset(mol);
         if (smiles_hint != "") {
             AssignBondOrderFromTemplateSMILES(this->rwmol, smiles_hint);
         }
         populateInternalAtomAndBondFromRWMol(seed);
         return true;
     }
populateFromSMILES()
bool SmolDock::Molecule::populateFromSMILES (const std::string & smiles, unsigned int seed = 36754)
Populate atoms and bonds from SMILES.
Populate atoms and bonds from SMILES. This uses the RDKit backend.
Parameters
smiles SMILES string
seed RNG seed
Returns
whether the parsing and initial conformer generation was successful.
See also
populateFromPDB()
Definition at line 41 of file Molecule.cpp.
References populateInternalAtomAndBondFromRWMol(), rwmol, and smiles.
{
         RDKit::RWMol *a = nullptr;
         try {
             /* This can throw */
             a = RDKit::SmilesToMol(smiles);
         }
         catch (...) {
             a = nullptr;
         }
         if (a == nullptr) {
             BOOST_LOG_TRIVIAL(error) << "Error in constructor Molecule::Molecule(const std::string &smiles)";
             BOOST_LOG_TRIVIAL(error) << "for smiles = " << smiles;
             BOOST_LOG_TRIVIAL(error) << "The SMILES string was not correctly parsed by RDKit.";
             BOOST_LOG_TRIVIAL(error)
                 << "This often indicated a malformed SMILES. (but not always, RDKit has parsing bugs)";
             return false;
         }
         this->rwmol.reset(a);
         if (this->populateInternalAtomAndBondFromRWMol(seed) == false)
             return false;
         this->smiles = smiles;
         return true;
     }
populateInternalAtomAndBondFromRWMol()
bool SmolDock::Molecule::populateInternalAtomAndBondFromRWMol (unsigned int seed) private
Use this if using RDKit RWMol as entry.
Definition at line 193 of file Molecule.cpp.
References atoms, bonds, SmolDock::Atom::carbon, SmolDock::Atom::hydrogen, initial_conformer_id, SmolDock::Atom::nitrogen, SmolDock::Atom::oxygen, and rwmol.
{
         // We care about Hs only during conformer generation
         // TODO: find out if we need to care at other moments...
         RDKit::MolOps::addHs(*(this->rwmol));
         this->initial_conformer_id = 0;
         if (this->rwmol->getNumConformers() == 0) // We need to generate the first conformer
         {
             this->initial_conformer_id = RDKit::DGeomHelpers::EmbedMolecule(*rwmol, 1000, seed, true);
         } else { // Else we will just use the first
             this->initial_conformer_id = (*(this->rwmol->beginConformers()))->getId();
         }
         RDKit::Conformer &starting_conformer = rwmol->getConformer(this->initial_conformer_id);
         // We remove them afterward
         RDKit::MolOps::removeHs((*(this->rwmol)));
         for (auto atom_it = rwmol->beginAtoms(); atom_it != rwmol->endAtoms(); ++atom_it) {
             std::shared_ptr<Atom> current_atom;
             // TODO : refactor this using the std::set of type-name-properties
             switch ((*atom_it)->getAtomicNum()) {
                 case 1:
                     current_atom = std::make_shared<Atom>(Atom::AtomType::hydrogen, (*atom_it)->getIdx());
                     break;
                 case 6:
                     current_atom = std::make_shared<Atom>(Atom::AtomType::carbon, (*atom_it)->getIdx());
                     break;
                 case 7:
                     current_atom = std::make_shared<Atom>(Atom::AtomType::nitrogen, (*atom_it)->getIdx());
                     break;
                 case 8:
                     current_atom = std::make_shared<Atom>(Atom::AtomType::oxygen, (*atom_it)->getIdx());
                     break;
                 default:
                     std::cout << "[!] Unsupported atom type" << std::endl;
                     std::cout << "[!] Atomic num = " << (*atom_it)->getAtomicNum() << std::endl;
                     return false;
                     // break;
             }
             const RDGeom::Point3D &position = starting_conformer.getAtomPos((*atom_it)->getIdx());
             current_atom->setAtomPosition(std::make_tuple(position.x, position.y, position.z));
             atoms.push_back(current_atom);
         }
         for (auto bond_it = rwmol->beginBonds(); bond_it != rwmol->endBonds(); ++bond_it) {
             auto beginAtom = (*bond_it)->getBeginAtom();
             auto endAtom = (*bond_it)->getEndAtom();
             unsigned int beginAtomID = beginAtom->getIdx();
             unsigned int endAtomID = endAtom->getIdx();
             auto resultBegin = std::find_if(std::begin(atoms), std::end(atoms),
                                             [beginAtomID](const std::shared_ptr<Atom> &atom) -> bool {
                                                 return atom->getAtomID() == beginAtomID;
                                             }
             );
             auto resultEnd = std::find_if(std::begin(atoms), std::end(atoms),
                                           [endAtomID](const std::shared_ptr<Atom> &atom) -> bool {
                                               return atom->getAtomID() == endAtomID;
                                           }
             );
             if (resultBegin == std::end(atoms) || resultEnd == std::end(atoms)) {
                 std::cout << "[!] Unable to find atom with ID = " << beginAtomID << " or " << endAtomID << std::endl;
                 return false;
             }
             auto new_bond = std::make_shared<Bond>(*resultBegin, *resultEnd);
             /*
               For reference, from RDKit's bond.h. We do not intent to support the exotic/dative bond for the
               foreseeable future.
               typedef enum {
                  UNSPECIFIED = 0,
                  SINGLE,
                  DOUBLE,
                  TRIPLE,
                  QUADRUPLE,
                  QUINTUPLE,
                  HEXTUPLE,
                  ONEANDAHALF,
                  TWOANDAHALF,
                  THREEANDAHALF,
                  FOURANDAHALF,
                  FIVEANDAHALF,
                  AROMATIC,
                  IONIC,
                  HYDROGEN,
                  THREECENTER,
                  DATIVEONE,  //!< one-electron dative (e.g. from a C in a Cp ring to a metal)
                  DATIVE,     //!< standard two-electron dative
                  DATIVEL,    //!< standard two-electron dative
                  DATIVER,    //!< standard two-electron dative
                  OTHER,
                  ZERO  //!< Zero-order bond (from
                  // http://pubs.acs.org/doi/abs/10.1021/ci200488k)
               } BondType;
              */
             switch ((*bond_it)->getBondType()) {
                 case RDKit::Bond::SINGLE:
                     new_bond->setBondType(Bond::BondType::singlebond);
                     break;
                 case RDKit::Bond::DOUBLE:
                     new_bond->setBondType(Bond::BondType::doublebond);
                     break;
                 case RDKit::Bond::TRIPLE:
                     new_bond->setBondType(Bond::BondType::triplebond);
                     break;
                 case RDKit::Bond::AROMATIC: // As expected aromatic is set for all bond in the cycle
                     // , not just the kekule-style "double bond"
                     new_bond->setBondType(Bond::BondType::aromatic);
                     break;
                 default:
                     std::cout << "[!] Unsupported bond type" << std::endl;
                     std::cout << "[!] Enum bond type = " << (*bond_it)->getBondType() << std::endl;
                     return false;
                     // break;
             }
             new_bond->publicizeToAtom();
             bonds.push_back(new_bond);
         }
         return true;
     }
setResidueName()
void SmolDock::Molecule::setResidueName (const std::string & res_name)
Set the 3-letter residue code used for this molecule in PDB file.
Parameters
res_name Residue name. Characters beyond the first three are ignored.
Returns
A 3-letter residue name string
See also
setResidueName()
Definition at line 188 of file Molecule.cpp.
References residue_name.
{
         this->residue_name = res_name.substr(0, 3);
     }
updateAtomPositionsFromiConformer()
bool SmolDock::Molecule::updateAtomPositionsFromiConformer (const iConformer & conformer)
Definition at line 324 of file Molecule.cpp.
References atoms, SmolDock::iConformer::x, SmolDock::iConformer::y, and SmolDock::iConformer::z.
{
         for (int i = 0; i < atoms.size(); ++i) {
             atoms[i]->setAtomPosition(
                     std::make_tuple(conformer.x[i], conformer.y[i], conformer.z[i])
             );
         }
         return true;
     }
Friends And Related Function Documentation
MoleculeTraversal
friend class MoleculeTraversal friend
Definition at line 55 of file Molecule.h.
PDBWriter
friend class PDBWriter friend
Definition at line 57 of file Molecule.h.
UnitTestHelper
friend class UnitTestHelper friend
Definition at line 56 of file Molecule.h.
Member Data Documentation
atoms
std::vector<std::shared_ptr<Atom> > SmolDock::Molecule::atoms private
Definition at line 151 of file Molecule.h.
bonds
std::vector<std::shared_ptr<Bond> > SmolDock::Molecule::bonds private
Definition at line 152 of file Molecule.h.
initial_conformer_id
int SmolDock::Molecule::initial_conformer_id = -1 private
Definition at line 163 of file Molecule.h.
residue_name
std::string SmolDock::Molecule::residue_name = "LIG" private
Definition at line 158 of file Molecule.h.
rwmol
std::shared_ptr<RDKit::RWMol> SmolDock::Molecule::rwmol private
Definition at line 154 of file Molecule.h.
smiles
std::string SmolDock::Molecule::smiles private
Definition at line 155 of file Molecule.h.
The documentation for this class was generated from the following files:
Molecule.h
Molecule.cpp