SmolDock: SmolDock::ReScorer Class Reference
SmolDock::ReScorer Class Reference
A simple wrapper to get docking scores from various score function for a given ligand-protein configuration.
#include <ReScorer.h>
Public Member Functions
ReScorer (Protein &prot, Molecule &mol, Score::ScoringFunctionType scorFuncType)
bool prepare ()
double getScore ()
Private Attributes
Protein & protein
Molecule & molecule
Score::ScoringFunctionType scoringFunctionType
std::shared_ptr< Score::ScoringFunction > scoringFunction
iProtein iprotein
iConformer iconformer
iTransform itransform
bool prepared = false
Detailed Description
A simple wrapper to get docking scores from various score function for a given ligand-protein configuration.
Definition at line 15 of file ReScorer.h.
Constructor & Destructor Documentation
ReScorer()
SmolDock::ReScorer::ReScorer (SmolDock::Protein & prot, SmolDock::Molecule & mol, Score::ScoringFunctionType scorFuncType)
Definition at line 15 of file ReScorer.cpp.
Member Function Documentation
getScore()
double SmolDock::ReScorer::getScore ()
Definition at line 35 of file ReScorer.cpp.
References prepared, and scoringFunction.
prepare()
bool SmolDock::ReScorer::prepare ()
Definition at line 22 of file ReScorer.cpp.
References SmolDock::Molecule::getInitialConformer(), SmolDock::Protein::getiProtein(), iconformer, iprotein, itransform, SmolDock::iTransformIdentityInit(), molecule, protein, scoringFunction, SmolDock::Score::scoringFunctionFactory(), and scoringFunctionType.
Member Data Documentation
iconformer
iConformer SmolDock::ReScorer::iconformer private
Definition at line 31 of file ReScorer.h.
iprotein
iProtein SmolDock::ReScorer::iprotein private
Definition at line 30 of file ReScorer.h.
itransform
iTransform SmolDock::ReScorer::itransform private
Definition at line 32 of file ReScorer.h.
molecule
Molecule& SmolDock::ReScorer::molecule private
Definition at line 25 of file ReScorer.h.
prepared
bool SmolDock::ReScorer::prepared = false private
Definition at line 34 of file ReScorer.h.
protein
Protein& SmolDock::ReScorer::protein private
Definition at line 24 of file ReScorer.h.
scoringFunction
std::shared_ptr<Score::ScoringFunction> SmolDock::ReScorer::scoringFunction private
Definition at line 28 of file ReScorer.h.
scoringFunctionType
Score::ScoringFunctionType SmolDock::ReScorer::scoringFunctionType private
Definition at line 26 of file ReScorer.h.
The documentation for this class was generated from the following files:
ReScorer.h
ReScorer.cpp