SmolDock: SmolDock::InputPostProcessor::VinaCompatibilityPostProcessor Class Reference
SmolDock::InputPostProcessor::VinaCompatibilityPostProcessor Class Reference
#include <VinaCompatibilityPostProcessor.h>
Public Member Functions
VinaCompatibilityPostProcessor ()=default
void processAtomFromLigand (SmolDock::Atom &atom) final
Modify the given atom of the ligand.
void processAtomFromProtein (SmolDock::Atom &atom, SmolDock::AminoAcid &residue) final
Modify the given atom of the protein.
~VinaCompatibilityPostProcessor () final=default
Public Member Functions inherited from SmolDock::InputPostProcessor::InputPostProcessor
virtual ~InputPostProcessor ()=default
Detailed Description
Definition at line 13 of file VinaCompatibilityPostProcessor.h.
Constructor & Destructor Documentation
VinaCompatibilityPostProcessor()
SmolDock::InputPostProcessor::VinaCompatibilityPostProcessor::VinaCompatibilityPostProcessor () default
~VinaCompatibilityPostProcessor()
SmolDock::InputPostProcessor::VinaCompatibilityPostProcessor::~VinaCompatibilityPostProcessor () final default
Member Function Documentation
processAtomFromLigand()
void SmolDock::InputPostProcessor::VinaCompatibilityPostProcessor::processAtomFromLigand (SmolDock::Atom & atom) final virtual
Modify the given atom of the ligand.
This fonction will be called for every atom of the ligand
It is garantueed that bonds will have been set and propagated to atoms when this function is called. It can use bonded atom for its determinations.
Parameters
atom An atom of the ligand
Implements SmolDock::InputPostProcessor::InputPostProcessor.
Definition at line 11 of file VinaCompatibilityPostProcessor.cpp.
processAtomFromProtein()
void SmolDock::InputPostProcessor::VinaCompatibilityPostProcessor::processAtomFromProtein (SmolDock::Atom & atom, SmolDock::AminoAcid & residue) final virtual
Modify the given atom of the protein.
This fonction will be called for every atom of the protein, with the residue it belongs to
Parameters
atom An atom of the protein
residue The amino acid containing such atom
Implements SmolDock::InputPostProcessor::InputPostProcessor.
Definition at line 16 of file VinaCompatibilityPostProcessor.cpp.
References SmolDock::AminoAcid::cysteine, SmolDock::Atom::getAtomType(), SmolDock::Atom::getAtomVariant(), SmolDock::AminoAcid::getType(), SmolDock::Atom::hydrogenAcceptor, SmolDock::Atom::hydrogenDonor, SmolDock::Atom::setAtomVariant(), and SmolDock::Atom::sulfur.
The documentation for this class was generated from the following files:
VinaCompatibilityPostProcessor.h
VinaCompatibilityPostProcessor.cpp