SmolDock: SmolDock::Score::VinaLikeRigidScoringFunction Class Reference
SmolDock::Score::VinaLikeRigidScoringFunction Class Reference
#include <VinaLikeRigidScoringFunction.h>
Public Member Functions
VinaLikeRigidScoringFunction (const iConformer &startingConformation_, const iProtein &p, const iTransform &initialTransform_, double differential_epsilon_=1e-3)
double Evaluate (const arma::mat &x) final
double EvaluateWithGradient (const arma::mat &x, arma::mat &gradient) final
arma::mat getStartingConditions () const final
double getDifferentialEpsilon () const final
iConformer getConformerForParamMatrix (const arma::mat &x) final
unsigned int getParamVectorDimension () const final
~VinaLikeRigidScoringFunction () final=default
Public Member Functions inherited from SmolDock::Score::ScoringFunction
virtual ~ScoringFunction ()=default
Private Member Functions
iTransform internalToExternalRepr (const arma::mat &x_) const
arma::mat externalToInternalRepr (const iTransform &tr_) const
Private Attributes
iConformer startingConformation
const iProtein & prot
const iTransform initialTransform
double differential_epsilon
Detailed Description
Definition at line 53 of file VinaLikeRigidScoringFunction.h.
Constructor & Destructor Documentation
VinaLikeRigidScoringFunction()
SmolDock::Score::VinaLikeRigidScoringFunction::VinaLikeRigidScoringFunction (const iConformer & startingConformation_, const iProtein & p, const iTransform & initialTransform_, double differential_epsilon_ = 1e-3)
Definition at line 212 of file VinaLikeRigidScoringFunction.cpp.
~VinaLikeRigidScoringFunction()
SmolDock::Score::VinaLikeRigidScoringFunction::~VinaLikeRigidScoringFunction () final default
Member Function Documentation
Evaluate()
double SmolDock::Score::VinaLikeRigidScoringFunction::Evaluate (const arma::mat & x) final virtual
Implements SmolDock::Score::ScoringFunction.
Definition at line 119 of file VinaLikeRigidScoringFunction.cpp.
References internalToExternalRepr(), SmolDock::normalizeQuaternionInPlace(), prot, SmolDock::iTransform::rota, startingConformation, and SmolDock::Score::vina_like_rigid_inter_scoring_func().
EvaluateWithGradient()
double SmolDock::Score::VinaLikeRigidScoringFunction::EvaluateWithGradient (const arma::mat & x, arma::mat & gradient) final virtual
Implements SmolDock::Score::ScoringFunction.
Definition at line 130 of file VinaLikeRigidScoringFunction.cpp.
References differential_epsilon, internalToExternalRepr(), SmolDock::normalizeQuaternionInPlace(), prot, SmolDock::iTransform::rota, startingConformation, SmolDock::iTransform::transl, and SmolDock::Score::vina_like_rigid_inter_scoring_func().
externalToInternalRepr()
arma::mat SmolDock::Score::VinaLikeRigidScoringFunction::externalToInternalRepr (const iTransform & tr_) const inline private
Definition at line 100 of file VinaLikeRigidScoringFunction.h.
References SmolDock::iTransform::rota, and SmolDock::iTransform::transl.
getConformerForParamMatrix()
iConformer SmolDock::Score::VinaLikeRigidScoringFunction::getConformerForParamMatrix (const arma::mat & x) final virtual
< Note that the internal representation arma::mat is not by itself normalized (because we always normalize it in the scoring function, so no constraint)
Implements SmolDock::Score::ScoringFunction.
Definition at line 231 of file VinaLikeRigidScoringFunction.cpp.
References SmolDock::applyRigidTransformInPlace(), internalToExternalRepr(), SmolDock::normalizeQuaternionInPlace(), SmolDock::iTransform::rota, and startingConformation.
getDifferentialEpsilon()
double SmolDock::Score::VinaLikeRigidScoringFunction::getDifferentialEpsilon () const final virtual
Implements SmolDock::Score::ScoringFunction.
Definition at line 223 of file VinaLikeRigidScoringFunction.cpp.
References differential_epsilon.
getParamVectorDimension()
unsigned int SmolDock::Score::VinaLikeRigidScoringFunction::getParamVectorDimension () const final virtual
Implements SmolDock::Score::ScoringFunction.
Definition at line 245 of file VinaLikeRigidScoringFunction.cpp.
getStartingConditions()
arma::mat SmolDock::Score::VinaLikeRigidScoringFunction::getStartingConditions () const final virtual
Implements SmolDock::Score::ScoringFunction.
Definition at line 227 of file VinaLikeRigidScoringFunction.cpp.
References externalToInternalRepr(), and initialTransform.
internalToExternalRepr()
iTransform SmolDock::Score::VinaLikeRigidScoringFunction::internalToExternalRepr (const arma::mat & x_) const inline private
Definition at line 83 of file VinaLikeRigidScoringFunction.h.
References SmolDock::iTransform::rota, and SmolDock::iTransform::transl.
Member Data Documentation
differential_epsilon
double SmolDock::Score::VinaLikeRigidScoringFunction::differential_epsilon private
Definition at line 118 of file VinaLikeRigidScoringFunction.h.
initialTransform
const iTransform SmolDock::Score::VinaLikeRigidScoringFunction::initialTransform private
Definition at line 117 of file VinaLikeRigidScoringFunction.h.
prot
const iProtein& SmolDock::Score::VinaLikeRigidScoringFunction::prot private
Definition at line 116 of file VinaLikeRigidScoringFunction.h.
startingConformation
iConformer SmolDock::Score::VinaLikeRigidScoringFunction::startingConformation private
Definition at line 115 of file VinaLikeRigidScoringFunction.h.
The documentation for this class was generated from the following files:
VinaLikeRigidScoringFunction.h
VinaLikeRigidScoringFunction.cpp