SmolDock: SmolDock::Heuristics::IteratedLocalSearch Class Reference
SmolDock::Heuristics::IteratedLocalSearch Class Reference
#include <IteratedLocalSearch.h>
Classes
struct Parameters
Public Member Functions
IteratedLocalSearch (Score::ScoringFunction *scorFunc_, Optimizer::Optimizer *optimizer_, unsigned int seed_, IteratedLocalSearch::Parameters params_)
bool search () final
arma::mat getResultMatrix () final
~IteratedLocalSearch () final=default
Public Member Functions inherited from SmolDock::Heuristics::GlobalHeuristic
virtual ~GlobalHeuristic ()=default
Private Attributes
Score::ScoringFunction * scorFunc
Optimizer::Optimizer * optimizer
std::mt19937 rndGenerator
arma::mat result
Parameters params
Detailed Description
Definition at line 16 of file IteratedLocalSearch.h.
Class Documentation
SmolDock::Heuristics::IteratedLocalSearch::Parameters
struct SmolDock::Heuristics::IteratedLocalSearch::Parameters
Definition at line 29 of file IteratedLocalSearch.h.
Class Members
double proteinMaxRadius
Constructor & Destructor Documentation
IteratedLocalSearch()
SmolDock::Heuristics::IteratedLocalSearch::IteratedLocalSearch (Score::ScoringFunction * scorFunc_, Optimizer::Optimizer * optimizer_, unsigned int seed_, IteratedLocalSearch::Parameters params_)
Definition at line 17 of file IteratedLocalSearch.cpp.
~IteratedLocalSearch()
SmolDock::Heuristics::IteratedLocalSearch::~IteratedLocalSearch () final default
Member Function Documentation
getResultMatrix()
arma::mat SmolDock::Heuristics::IteratedLocalSearch::getResultMatrix () final virtual
Implements SmolDock::Heuristics::GlobalHeuristic.
Definition at line 137 of file IteratedLocalSearch.cpp.
References result.
search()
bool SmolDock::Heuristics::IteratedLocalSearch::search () final virtual
Implements SmolDock::Heuristics::GlobalHeuristic.
Definition at line 23 of file IteratedLocalSearch.cpp.
References SmolDock::Score::ScoringFunction::Evaluate(), SmolDock::Optimizer::Optimizer::getRawResultMatrix(), SmolDock::Optimizer::Optimizer::getScore(), SmolDock::Score::ScoringFunction::getStartingConditions(), SmolDock::Heuristics::MetropolisAccept(), SmolDock::Optimizer::Optimizer::optimize(), optimizer, params, SmolDock::Heuristics::IteratedLocalSearch::Parameters::proteinMaxRadius, result, rndGenerator, and scorFunc.
Member Data Documentation
optimizer
Optimizer::Optimizer* SmolDock::Heuristics::IteratedLocalSearch::optimizer private
Definition at line 37 of file IteratedLocalSearch.h.
params
Parameters SmolDock::Heuristics::IteratedLocalSearch::params private
Definition at line 43 of file IteratedLocalSearch.h.
result
arma::mat SmolDock::Heuristics::IteratedLocalSearch::result private
Definition at line 41 of file IteratedLocalSearch.h.
rndGenerator
std::mt19937 SmolDock::Heuristics::IteratedLocalSearch::rndGenerator private
Definition at line 39 of file IteratedLocalSearch.h.
scorFunc
Score::ScoringFunction* SmolDock::Heuristics::IteratedLocalSearch::scorFunc private
Definition at line 36 of file IteratedLocalSearch.h.
The documentation for this class was generated from the following files:
IteratedLocalSearch.h
IteratedLocalSearch.cpp