SmolDock: SmolDock::IntermediateConformerCollector Class Reference
SmolDock::IntermediateConformerCollector Class Reference
#include <IntermediateConformerCollector.h>
Public Member Functions
IntermediateConformerCollector (Molecule *mol, PDBWriter *pdbwriter)
void addiConformer (iConformer conformer)
Private Attributes
Molecule * molecule = nullptr
PDBWriter * writer = nullptr
Detailed Description
Definition at line 13 of file IntermediateConformerCollector.h.
Constructor & Destructor Documentation
IntermediateConformerCollector()
SmolDock::IntermediateConformerCollector::IntermediateConformerCollector (Molecule * mol, PDBWriter * pdbwriter)
Definition at line 19 of file IntermediateConformerCollector.cpp.
Member Function Documentation
addiConformer()
void SmolDock::IntermediateConformerCollector::addiConformer (iConformer conformer)
Definition at line 13 of file IntermediateConformerCollector.cpp.
References SmolDock::PDBWriter::addLigand(), SmolDock::Molecule::deepcopy(), molecule, SmolDock::Molecule::updateAtomPositionsFromiConformer(), and writer.
Member Data Documentation
molecule
Molecule* SmolDock::IntermediateConformerCollector::molecule = nullptr private
Definition at line 19 of file IntermediateConformerCollector.h.
writer
PDBWriter* SmolDock::IntermediateConformerCollector::writer = nullptr private
Definition at line 20 of file IntermediateConformerCollector.h.
The documentation for this class was generated from the following files:
IntermediateConformerCollector.h
IntermediateConformerCollector.cpp