SmolDock: SmolDock::Heuristics::RandomRestart Class Reference
SmolDock::Heuristics::RandomRestart Class Reference
#include <RandomRestart.h>
Classes
struct Parameters
Public Member Functions
RandomRestart (Score::ScoringFunction *scorFunc_, Optimizer::Optimizer *optimizer_, unsigned int seed_, RandomRestart::Parameters params_)
bool search () final
arma::mat getResultMatrix () final
~RandomRestart () final=default
Public Member Functions inherited from SmolDock::Heuristics::GlobalHeuristic
virtual ~GlobalHeuristic ()=default
Private Attributes
Score::ScoringFunction * scorFunc
Optimizer::Optimizer * optimizer
std::mt19937 rndGenerator
arma::mat result
Parameters params
Detailed Description
Definition at line 16 of file RandomRestart.h.
Class Documentation
SmolDock::Heuristics::RandomRestart::Parameters
struct SmolDock::Heuristics::RandomRestart::Parameters
Definition at line 31 of file RandomRestart.h.
Class Members
double proteinMaxRadius
Constructor & Destructor Documentation
RandomRestart()
SmolDock::Heuristics::RandomRestart::RandomRestart (Score::ScoringFunction * scorFunc_, Optimizer::Optimizer * optimizer_, unsigned int seed_, RandomRestart::Parameters params_)
Definition at line 16 of file RandomRestart.cpp.
~RandomRestart()
SmolDock::Heuristics::RandomRestart::~RandomRestart () final default
Member Function Documentation
getResultMatrix()
arma::mat SmolDock::Heuristics::RandomRestart::getResultMatrix () final virtual
Implements SmolDock::Heuristics::GlobalHeuristic.
Definition at line 66 of file RandomRestart.cpp.
References result.
search()
bool SmolDock::Heuristics::RandomRestart::search () final virtual
Implements SmolDock::Heuristics::GlobalHeuristic.
Definition at line 22 of file RandomRestart.cpp.
References SmolDock::Score::ScoringFunction::Evaluate(), SmolDock::Optimizer::Optimizer::getRawResultMatrix(), SmolDock::Optimizer::Optimizer::getScore(), SmolDock::Score::ScoringFunction::getStartingConditions(), SmolDock::Optimizer::Optimizer::optimize(), optimizer, params, SmolDock::Heuristics::RandomRestart::Parameters::proteinMaxRadius, result, rndGenerator, and scorFunc.
Member Data Documentation
optimizer
Optimizer::Optimizer* SmolDock::Heuristics::RandomRestart::optimizer private
Definition at line 39 of file RandomRestart.h.
params
Parameters SmolDock::Heuristics::RandomRestart::params private
Definition at line 45 of file RandomRestart.h.
result
arma::mat SmolDock::Heuristics::RandomRestart::result private
Definition at line 43 of file RandomRestart.h.
rndGenerator
std::mt19937 SmolDock::Heuristics::RandomRestart::rndGenerator private
Definition at line 41 of file RandomRestart.h.
scorFunc
Score::ScoringFunction* SmolDock::Heuristics::RandomRestart::scorFunc private
Definition at line 38 of file RandomRestart.h.
The documentation for this class was generated from the following files:
RandomRestart.h
RandomRestart.cpp