SmolDock: SmolDock::Engine::PoseRefiner Class Reference
SmolDock::Engine::PoseRefiner Class Reference
#include <PoseRefiner.h>
Public Member Functions
PoseRefiner (Protein *protein, Molecule *ligand, Score::ScoringFunctionType scFuncType, Optimizer::LocalOptimizerType localOptimizerType_, unsigned int seed)
bool refinePose ()
double getInitialScore ()
double getFinalScore ()
double getScoreDifference ()
bool applyToLigand ()
Private Attributes
Protein * orig_protein
Molecule * orig_ligand
Score::ScoringFunctionType scoringFuncType
Optimizer::LocalOptimizerType localOptimizerType
std::shared_ptr< Score::ScoringFunction > scoringFunction
std::shared_ptr< Heuristics::GlobalHeuristic > globalHeuristic
std::shared_ptr< Optimizer::Optimizer > localOptimizer
std::mt19937 rnd_generator
iProtein protein
double initial_score = 0.0
double final_score = 0.0
iConformer result
Detailed Description
Definition at line 16 of file PoseRefiner.h.
Constructor & Destructor Documentation
PoseRefiner()
SmolDock::Engine::PoseRefiner::PoseRefiner (Protein * protein, Molecule * ligand, Score::ScoringFunctionType scFuncType, Optimizer::LocalOptimizerType localOptimizerType_, unsigned int seed)
Definition at line 12 of file PoseRefiner.cpp.
Member Function Documentation
applyToLigand()
bool SmolDock::Engine::PoseRefiner::applyToLigand ()
Definition at line 81 of file PoseRefiner.cpp.
References orig_ligand, result, and SmolDock::Molecule::updateAtomPositionsFromiConformer().
getFinalScore()
double SmolDock::Engine::PoseRefiner::getFinalScore ()
Definition at line 73 of file PoseRefiner.cpp.
References final_score.
getInitialScore()
double SmolDock::Engine::PoseRefiner::getInitialScore ()
Definition at line 69 of file PoseRefiner.cpp.
References initial_score.
getScoreDifference()
double SmolDock::Engine::PoseRefiner::getScoreDifference ()
Definition at line 77 of file PoseRefiner.cpp.
References final_score, and initial_score.
refinePose()
bool SmolDock::Engine::PoseRefiner::refinePose ()
Definition at line 23 of file PoseRefiner.cpp.
References SmolDock::iConformer::centroidNormalizingTransform, final_score, SmolDock::Molecule::getInitialConformer(), SmolDock::Protein::getiProtein(), globalHeuristic, SmolDock::Heuristics::globalHeuristicFactory(), SmolDock::Heuristics::heuristicParametersFactory(), initial_score, SmolDock::iTransformIdentityInit(), localOptimizer, localOptimizerType, SmolDock::Heuristics::OnlyLocal, SmolDock::Optimizer::optimizerFactory(), orig_ligand, orig_protein, protein, result, rnd_generator, scoringFunction, SmolDock::Score::scoringFunctionFactory(), scoringFuncType, and SmolDock::iTransform::transl.
Member Data Documentation
final_score
double SmolDock::Engine::PoseRefiner::final_score = 0.0 private
Definition at line 50 of file PoseRefiner.h.
globalHeuristic
std::shared_ptr<Heuristics::GlobalHeuristic> SmolDock::Engine::PoseRefiner::globalHeuristic private
Definition at line 42 of file PoseRefiner.h.
initial_score
double SmolDock::Engine::PoseRefiner::initial_score = 0.0 private
Definition at line 49 of file PoseRefiner.h.
localOptimizer
std::shared_ptr<Optimizer::Optimizer> SmolDock::Engine::PoseRefiner::localOptimizer private
Definition at line 43 of file PoseRefiner.h.
localOptimizerType
Optimizer::LocalOptimizerType SmolDock::Engine::PoseRefiner::localOptimizerType private
Definition at line 39 of file PoseRefiner.h.
orig_ligand
Molecule* SmolDock::Engine::PoseRefiner::orig_ligand private
Definition at line 36 of file PoseRefiner.h.
orig_protein
Protein* SmolDock::Engine::PoseRefiner::orig_protein private
Definition at line 35 of file PoseRefiner.h.
protein
iProtein SmolDock::Engine::PoseRefiner::protein private
Definition at line 47 of file PoseRefiner.h.
result
iConformer SmolDock::Engine::PoseRefiner::result private
Definition at line 52 of file PoseRefiner.h.
rnd_generator
std::mt19937 SmolDock::Engine::PoseRefiner::rnd_generator private
Definition at line 45 of file PoseRefiner.h.
scoringFunction
std::shared_ptr<Score::ScoringFunction> SmolDock::Engine::PoseRefiner::scoringFunction private
Definition at line 41 of file PoseRefiner.h.
scoringFuncType
Score::ScoringFunctionType SmolDock::Engine::PoseRefiner::scoringFuncType private
Definition at line 38 of file PoseRefiner.h.
The documentation for this class was generated from the following files:
PoseRefiner.h
PoseRefiner.cpp