SmolDock: SmolDock::Heuristics::OnlyLocal Class Reference
SmolDock::Heuristics::OnlyLocal Class Reference
#include <OnlyLocal.h>
Classes
struct Parameters
Public Member Functions
OnlyLocal (Score::ScoringFunction *scorFunc_, Optimizer::Optimizer *optimizer_, unsigned int seed_, OnlyLocal::Parameters params_)
bool search () final
arma::mat getResultMatrix () final
~OnlyLocal () final=default
Public Member Functions inherited from SmolDock::Heuristics::GlobalHeuristic
virtual ~GlobalHeuristic ()=default
Private Attributes
Score::ScoringFunction * scorFunc
Optimizer::Optimizer * optimizer
std::mt19937 rnd_generator
arma::mat result
Parameters params
Detailed Description
Definition at line 16 of file OnlyLocal.h.
Class Documentation
SmolDock::Heuristics::OnlyLocal::Parameters
struct SmolDock::Heuristics::OnlyLocal::Parameters
Definition at line 31 of file OnlyLocal.h.
Constructor & Destructor Documentation
OnlyLocal()
SmolDock::Heuristics::OnlyLocal::OnlyLocal (Score::ScoringFunction * scorFunc_, Optimizer::Optimizer * optimizer_, unsigned int seed_, OnlyLocal::Parameters params_)
Definition at line 10 of file OnlyLocal.cpp.
~OnlyLocal()
SmolDock::Heuristics::OnlyLocal::~OnlyLocal () final default
Member Function Documentation
getResultMatrix()
arma::mat SmolDock::Heuristics::OnlyLocal::getResultMatrix () final virtual
Implements SmolDock::Heuristics::GlobalHeuristic.
Definition at line 26 of file OnlyLocal.cpp.
References result.
search()
bool SmolDock::Heuristics::OnlyLocal::search () final virtual
Implements SmolDock::Heuristics::GlobalHeuristic.
Definition at line 16 of file OnlyLocal.cpp.
References SmolDock::Optimizer::Optimizer::getRawResultMatrix(), SmolDock::Score::ScoringFunction::getStartingConditions(), SmolDock::Optimizer::Optimizer::optimize(), optimizer, result, and scorFunc.
Member Data Documentation
optimizer
Optimizer::Optimizer* SmolDock::Heuristics::OnlyLocal::optimizer private
Definition at line 36 of file OnlyLocal.h.
params
Parameters SmolDock::Heuristics::OnlyLocal::params private
Definition at line 42 of file OnlyLocal.h.
result
arma::mat SmolDock::Heuristics::OnlyLocal::result private
Definition at line 40 of file OnlyLocal.h.
rnd_generator
std::mt19937 SmolDock::Heuristics::OnlyLocal::rnd_generator private
Definition at line 38 of file OnlyLocal.h.
scorFunc
Score::ScoringFunction* SmolDock::Heuristics::OnlyLocal::scorFunc private
Definition at line 35 of file OnlyLocal.h.
The documentation for this class was generated from the following files:
OnlyLocal.h
OnlyLocal.cpp