SmolDock: SmolDock::Engine::ConformerRigidDockingEngine Class Reference
SmolDock::Engine::ConformerRigidDockingEngine Class Reference
Generates a lot of conformer, then runs rigid docking on them.
#include <ConformerRigidDockingEngine.h>
Public Member Functions
ConformerRigidDockingEngine (unsigned int conformer_num)
bool setDockingBox (DockingBoxSetting setting) final
Set the protein domain/box to consider for docking.
bool setProtein (Protein *p) final
Load a protein for docking.
bool setLigand (Molecule *m) final
Load a molecule ligand for docking.
void setRandomSeed (int seed) final
Set the RNG seed for reproducibility.
bool setupDockingEngine () final
Prepare the engine for docking.
void runDockingEngine () final
Run the docking.
std::shared_ptr< DockingResult > getDockingResult () final
Get the docking results.
Private Attributes
unsigned int conformer_num
Protein * orig_protein
Molecule * orig_ligand
int random_seed = 1
std::mt19937 rnd_generator
std::shared_ptr< RDKit::RWMol > rwmol
std::vector< iConformer > viConformers
iProtein protein
Additional Inherited Members
Public Types inherited from SmolDock::Engine::AbstractDockingEngine
enum DockingBoxSetting { DockingBoxSetting::everything, DockingBoxSetting::solventExposed }
enum DockingBoxShape { DockingBoxShape::sphere, DockingBoxShape::cube }
Detailed Description
Generates a lot of conformer, then runs rigid docking on them.
The general idea is generating lots of conformer, then docking them with constant bond angle and distance ("rigid" docking). The theory being that this may be faster than real docking and still produce a similar affinity ranking. (In practice, I do not know if it would work : hence this to try it
Definition at line 42 of file ConformerRigidDockingEngine.h.
Constructor & Destructor Documentation
ConformerRigidDockingEngine()
SmolDock::Engine::ConformerRigidDockingEngine::ConformerRigidDockingEngine (unsigned int conformer_num) explicit
Parameters
conformer_num Number of conformer to generate
Definition at line 61 of file ConformerRigidDockingEngine.cpp.
References conformer_num.
{
             this->conformer_num = conformer_num;
             assert(conformer_num != 0);
         }
Member Function Documentation
getDockingResult()
std::shared_ptr< DockingResult > SmolDock::Engine::ConformerRigidDockingEngine::getDockingResult () final virtual
Get the docking results.
Behaviour is undefined if called before runDockingEngine()
Returns
The results of the docking.
See also
runDockingEngine()
Implements SmolDock::Engine::AbstractDockingEngine.
Definition at line 259 of file ConformerRigidDockingEngine.cpp.
{
             return std::make_shared<DockingResult>();
         }
runDockingEngine()
void SmolDock::Engine::ConformerRigidDockingEngine::runDockingEngine () final virtual
Run the docking.
Returns
Returns whether it has been successful
See also
Implements SmolDock::Engine::AbstractDockingEngine.
Definition at line 124 of file ConformerRigidDockingEngine.cpp.
References SmolDock::Score::basic_scoring_func(), conformer_num, SmolDock::iGradient::dx, SmolDock::iGradient::dy, SmolDock::iGradient::dz, SmolDock::iTransformZeroInit(), protein, record_timings, SmolDock::iTransform::transl, viConformers, SmolDock::iTranslation::x, SmolDock::iTranslation::y, and SmolDock::iTranslation::z.
{
             using namespace boost::accumulators;
             accumulator_set<double, stats<tag::mean, tag::moment<2> > > acc_score;
             accumulator_set<double, stats<tag::mean, tag::moment<2> > > acc_duration;
             std::vector<double> scores;
             scores.reserve(this->conformer_num);
             record_timings(begin_docking);
             for(auto& conformer : this->viConformers)
             {
                 record_timings(begin_docking_this_conformer);
                 iTransform transform = iTransformZeroInit();
                 iGradient translationGradient;
                 double score = Score::basic_scoring_func(conformer,transform, this->protein);
                 double oldscore;
                 double score_progress = 100.0;
                 double differential_epsilon = 0.01;
                 unsigned int iterationNbr = 0;
                 while(score_progress > 0.001 )
                 {
                     oldscore = score;
                     // Compute approx gradient to find in which direction to go
                     iTransform transform_dx = transform;
                     transform_dx.transl.x += differential_epsilon;
                     translationGradient.dx = oldscore - Score::basic_scoring_func(conformer,transform_dx, this->protein);
                     iTransform transform_dy = transform;
                     transform_dy.transl.y += differential_epsilon;
                     translationGradient.dy = oldscore -  Score::basic_scoring_func(conformer,transform_dy, this->protein);
                     iTransform transform_dz = transform;
                     transform_dz.transl.z += differential_epsilon;
                     translationGradient.dz = oldscore - Score::basic_scoring_func(conformer,transform_dz, this->protein);
                     // Now we want to know how far in that direction
                     // We do a line-search
                     iTransform transform_linesearch;
                     double step = 0.0001;
                     double previous_step = 0.0;
                     double temp_score;
                     double previous_temp_score = std::numeric_limits<double>::max();
                     // We go further and further in the direction of the gradient, until we are not bettering the score
                     while(true) {
                         transform_linesearch = transform;
                         transform_linesearch.transl.x  += step * translationGradient.dx;
                         transform_linesearch.transl.y  += step * translationGradient.dy;
                         transform_linesearch.transl.z  += step * translationGradient.dz;
                         temp_score = Score::basic_scoring_func(conformer, transform_linesearch, this->protein);
                         double diff_oldscore_tempscore = oldscore - temp_score;
                         double diff_previous_tempscore = previous_temp_score - temp_score;
                         previous_temp_score = temp_score;
                         if (diff_oldscore_tempscore > 0 && // temp_score is lower than the old score thus better
                             diff_previous_tempscore > 0 ) // It is also lower than in the previous iteration
{
                             // so we jump further to see if it can be even better
                             previous_step = step;
                             step = step * 10;
                             continue;
                         } else {
                             // We hit a step that is not better than either oldscore or the previous iterator
                             break;
                         }
                     }
                     // We then go back to previous_step for updating the score
                     if(previous_step == 0.0)
                     {
                         // This means we could not do any jump forward
                         // So this is the best we can do (to the precision of the starting step 0.0001 (angstrom))
                         // So we stop the search (this is one of the stop condition, the other is score_progress)
                         break;
                     }
                     // Otherwise we update the transform and go for another round
                     transform.transl.x  += previous_step * translationGradient.dx;
                     transform.transl.y  += previous_step * translationGradient.dy;
                     transform.transl.z  += previous_step * translationGradient.dz;
                     score = Score::basic_scoring_func(conformer,transform, this->protein);
                     score_progress = oldscore - score;
                     iterationNbr++;
                     //BOOST_LOG_TRIVIAL(debug) << "     Score: " << score << " (progress: "<< score_progress <<  " )";
                 }
                 scores.push_back(score);
                 record_timings(end_docking_this_conformer);
                 acc_score(score);
                 acc_duration(
                         static_cast< std::chrono::duration<double> >(end_docking_this_conformer - begin_docking_this_conformer).count()
                         );
             }
             record_timings(end_docking);
 #ifdef SMOLDOCK_VERBOSE_DEBUG
             auto total_docking_duration = static_cast< std::chrono::duration<double> >(end_docking - begin_docking).count();
             BOOST_LOG_TRIVIAL(debug) << "Timings ConformerRigidDockingEngine docking runs"
                                      << "\n      TOTAL: " << total_docking_duration << "s"
                                      << "\n      Mean per conformer: " << mean(acc_duration) << "s"
                                      << "\n      StdDev per conformer: " << std::sqrt(moment<2>(acc_duration)) << "s";
 #endif
             BOOST_LOG_TRIVIAL(info) << "Results:";
             BOOST_LOG_TRIVIAL(info) << "   Score Mean: " << mean(acc_score);
             BOOST_LOG_TRIVIAL(info) << "   Score StdDev: " << std::sqrt(moment<2>(acc_score));
             BOOST_LOG_TRIVIAL(info) << "   Scores: ";
             for(auto& score: scores)
             {
                 BOOST_LOG_TRIVIAL(info) << "      " << score;
             }
         }
setDockingBox()
bool SmolDock::Engine::ConformerRigidDockingEngine::setDockingBox (DockingBoxSetting setting) final virtual
Set the protein domain/box to consider for docking.
A restriction of the search space can be necessary : this provides a way to specify a domain/box in the protein where the docking will take place.
Parameters
setting General-scope DockingBox specification
Returns
Returns whether it has been successful
See also
setProtein(), setLigand()
Implements SmolDock::Engine::AbstractDockingEngine.
Definition at line 264 of file ConformerRigidDockingEngine.cpp.
References SmolDock::Engine::AbstractDockingEngine::everything.
{
             if (setting != DockingBoxSetting::everything) {
                 std::cout << "[!] DockingBoxSetting (that is not DockingBoxSetting::everything) is not yet implemented."
                           << std::endl;
                 std::cout << "[ ] Running as if DockingBoxSetting::everything was passed" << std::endl;
                 return false;
             }
             return true;
         }
setLigand()
bool SmolDock::Engine::ConformerRigidDockingEngine::setLigand (Molecule * m) final virtual
Load a molecule ligand for docking.
Load a molecule ligand for docking. Note that it can be modified by the engine.
Parameters
m Pointer to the Molecule
Returns
Returns whether it has been successful
See also
setProtein(), setDockingBox()
Implements SmolDock::Engine::AbstractDockingEngine.
Definition at line 71 of file ConformerRigidDockingEngine.cpp.
References SmolDock::Molecule::getInternalRWMol(), orig_ligand, and rwmol.
{
             this->orig_ligand = m;
             // Getting a handle on the RWMol
             this->rwmol = this->orig_ligand->getInternalRWMol();
             return true;
         }
setProtein()
bool SmolDock::Engine::ConformerRigidDockingEngine::setProtein (Protein * p) final virtual
Load a protein for docking.
Load a protein for docking. Note that it can be modified by the engine.
Parameters
p Pointer to the Protein
Returns
Returns whether it has been successful
See also
setLigand(), setDockingBox()
Implements SmolDock::Engine::AbstractDockingEngine.
Definition at line 66 of file ConformerRigidDockingEngine.cpp.
References orig_protein.
{
             this->orig_protein = p;
             return true;
         }
setRandomSeed()
void SmolDock::Engine::ConformerRigidDockingEngine::setRandomSeed (int seed) final virtual
Set the RNG seed for reproducibility.
Parameters
seed RNG see
Returns
Returns whether it has been successful
See also
setProtein(), setLigand(), setDockingBox()
Implements SmolDock::Engine::AbstractDockingEngine.
Definition at line 275 of file ConformerRigidDockingEngine.cpp.
References random_seed, and rnd_generator.
{
             this->random_seed = seed;
             this->rnd_generator.seed(this->random_seed);
         }
setupDockingEngine()
bool SmolDock::Engine::ConformerRigidDockingEngine::setupDockingEngine () final virtual
Prepare the engine for docking.
Prepare the engine for docking. It is expected in future versions to separate protein, ligand, and prot-ligand initilization, so as to allow maximum work sharing in screening scenario (same prot = same prot prep, just different ligand)
Returns
Returns whether it has been successful
See also
Implements SmolDock::Engine::AbstractDockingEngine.
Definition at line 81 of file ConformerRigidDockingEngine.cpp.
References conformer_num, SmolDock::Molecule::generateConformers(), SmolDock::Protein::getiProtein(), orig_ligand, orig_protein, protein, record_timings, rnd_generator, and viConformers.
{
             record_timings(begin_setup);
             std::uniform_int_distribution<> dis(0, std::numeric_limits<int>::max());
             record_timings(begin_conformersgen);
             auto seed = dis(this->rnd_generator);
             BOOST_LOG_TRIVIAL(debug) << "Seed : " << seed;
             this->orig_ligand->generateConformers(this->viConformers, this->conformer_num, seed);
             record_timings(end_conformersgen);
             this->protein = this->orig_protein->getiProtein();
             record_timings(end_iprotgen);
             record_timings(end_setup);
 #ifdef SMOLDOCK_VERBOSE_DEBUG
             auto total_setup_duration = static_cast< std::chrono::duration<double> >(end_setup - begin_setup).count();
             auto duration_conformergen = static_cast< std::chrono::duration<double> >(end_conformersgen - begin_conformersgen).count();
             auto duration_iprot = static_cast< std::chrono::duration<double> >(end_iprotgen - end_conformersgen).count();
             BOOST_LOG_TRIVIAL(debug) << "Timings ConformerRigidDockingEngine setup"
                                 <<"\n      TOTAL: "
                                   << total_setup_duration << "s"
                                   << "\n      Conformer: "
                                   << duration_conformergen
                                   <<"s [n=" << this->conformer_num << "->" << this->viConformers.size() << "] "
                                   << duration_conformergen/this->conformer_num << "s each"
                                   << "\n      iProt: " << duration_iprot << "s";
 #endif
             BOOST_LOG_TRIVIAL(info) << "Conformer docking engine: ready";
             return true;
         }
Member Data Documentation
conformer_num
unsigned int SmolDock::Engine::ConformerRigidDockingEngine::conformer_num private
Definition at line 73 of file ConformerRigidDockingEngine.h.
orig_ligand
Molecule* SmolDock::Engine::ConformerRigidDockingEngine::orig_ligand private
Definition at line 76 of file ConformerRigidDockingEngine.h.
orig_protein
Protein* SmolDock::Engine::ConformerRigidDockingEngine::orig_protein private
Definition at line 75 of file ConformerRigidDockingEngine.h.
protein
iProtein SmolDock::Engine::ConformerRigidDockingEngine::protein private
Definition at line 85 of file ConformerRigidDockingEngine.h.
random_seed
int SmolDock::Engine::ConformerRigidDockingEngine::random_seed = 1 private
Definition at line 78 of file ConformerRigidDockingEngine.h.
rnd_generator
std::mt19937 SmolDock::Engine::ConformerRigidDockingEngine::rnd_generator private
Definition at line 79 of file ConformerRigidDockingEngine.h.
rwmol
std::shared_ptr<RDKit::RWMol> SmolDock::Engine::ConformerRigidDockingEngine::rwmol private
Definition at line 81 of file ConformerRigidDockingEngine.h.
viConformers
std::vector<iConformer> SmolDock::Engine::ConformerRigidDockingEngine::viConformers private
Definition at line 83 of file ConformerRigidDockingEngine.h.
The documentation for this class was generated from the following files:
ConformerRigidDockingEngine.h
ConformerRigidDockingEngine.cpp