SmolDock: SmolDock::Score::VinaLikeScoringFunction Class Reference
SmolDock::Score::VinaLikeScoringFunction Class Reference
#include <VinaLikeScoringFunction.h>
Public Member Functions
VinaLikeScoringFunction (const iConformer &startingConformation_, const iProtein &p, const iTransform &initialTransform_, double differential_epsilon_=1e-3)
double Evaluate (const arma::mat &x) final
double EvaluateWithGradient (const arma::mat &x, arma::mat &gradient) final
arma::mat getStartingConditions () const final
double getDifferentialEpsilon () const final
iConformer getConformerForParamMatrix (const arma::mat &x) final
unsigned int getParamVectorDimension () const final
~VinaLikeScoringFunction () final=default
Public Member Functions inherited from SmolDock::Score::ScoringFunction
virtual ~ScoringFunction ()=default
Private Member Functions
iTransform internalToExternalRepr (const arma::mat &x_) const
arma::mat externalToInternalRepr (const iTransform &tr_) const
Private Attributes
iConformer startingConformation
const iProtein & prot
const iTransform initialTransform
double differential_epsilon
unsigned int numberOfParamInState
unsigned int numberOfRotatableBonds
Detailed Description
Definition at line 22 of file VinaLikeScoringFunction.h.
Constructor & Destructor Documentation
VinaLikeScoringFunction()
SmolDock::Score::VinaLikeScoringFunction::VinaLikeScoringFunction (const iConformer & startingConformation_, const iProtein & p, const iTransform & initialTransform_, double differential_epsilon_ = 1e-3)
Definition at line 85 of file VinaLikeScoringFunction.cpp.
References SmolDock::iTransform::bondRotationsAngles, initialTransform, SmolDock::iConformer::num_rotatable_bond, numberOfParamInState, numberOfRotatableBonds, and startingConformation.
~VinaLikeScoringFunction()
SmolDock::Score::VinaLikeScoringFunction::~VinaLikeScoringFunction () final default
Member Function Documentation
Evaluate()
double SmolDock::Score::VinaLikeScoringFunction::Evaluate (const arma::mat & x) final virtual
Implements SmolDock::Score::ScoringFunction.
Definition at line 107 of file VinaLikeScoringFunction.cpp.
References internalToExternalRepr(), SmolDock::normalizeQuaternionInPlace(), prot, SmolDock::iTransform::rota, startingConformation, and SmolDock::Score::VinaLikeIntermolecularScoringFunction().
EvaluateWithGradient()
double SmolDock::Score::VinaLikeScoringFunction::EvaluateWithGradient (const arma::mat & x, arma::mat & gradient) final virtual
Implements SmolDock::Score::ScoringFunction.
Definition at line 119 of file VinaLikeScoringFunction.cpp.
References SmolDock::iTransform::bondRotationsAngles, differential_epsilon, internalToExternalRepr(), SmolDock::normalizeQuaternionInPlace(), numberOfRotatableBonds, prot, SmolDock::iTransform::rota, startingConformation, SmolDock::iTransform::transl, and SmolDock::Score::VinaLikeIntermolecularScoringFunction().
externalToInternalRepr()
arma::mat SmolDock::Score::VinaLikeScoringFunction::externalToInternalRepr (const iTransform & tr_) const inline private
Definition at line 71 of file VinaLikeScoringFunction.h.
References SmolDock::iTransform::bondRotationsAngles, numberOfParamInState, numberOfRotatableBonds, SmolDock::iTransform::rota, and SmolDock::iTransform::transl.
getConformerForParamMatrix()
iConformer SmolDock::Score::VinaLikeScoringFunction::getConformerForParamMatrix (const arma::mat & x) final virtual
Implements SmolDock::Score::ScoringFunction.
Definition at line 221 of file VinaLikeScoringFunction.cpp.
References SmolDock::applyBondRotationInPlace(), SmolDock::applyRigidTransformInPlace(), internalToExternalRepr(), SmolDock::iTransform::rota, and startingConformation.
getDifferentialEpsilon()
double SmolDock::Score::VinaLikeScoringFunction::getDifferentialEpsilon () const final virtual
Implements SmolDock::Score::ScoringFunction.
Definition at line 213 of file VinaLikeScoringFunction.cpp.
References differential_epsilon.
getParamVectorDimension()
unsigned int SmolDock::Score::VinaLikeScoringFunction::getParamVectorDimension () const final virtual
Implements SmolDock::Score::ScoringFunction.
Definition at line 234 of file VinaLikeScoringFunction.cpp.
References numberOfParamInState.
getStartingConditions()
arma::mat SmolDock::Score::VinaLikeScoringFunction::getStartingConditions () const final virtual
Implements SmolDock::Score::ScoringFunction.
Definition at line 217 of file VinaLikeScoringFunction.cpp.
References externalToInternalRepr(), and initialTransform.
internalToExternalRepr()
iTransform SmolDock::Score::VinaLikeScoringFunction::internalToExternalRepr (const arma::mat & x_) const inline private
Definition at line 50 of file VinaLikeScoringFunction.h.
References SmolDock::iTransform::bondRotationsAngles, numberOfRotatableBonds, SmolDock::iTransform::rota, and SmolDock::iTransform::transl.
Member Data Documentation
differential_epsilon
double SmolDock::Score::VinaLikeScoringFunction::differential_epsilon private
Definition at line 93 of file VinaLikeScoringFunction.h.
initialTransform
const iTransform SmolDock::Score::VinaLikeScoringFunction::initialTransform private
Definition at line 92 of file VinaLikeScoringFunction.h.
numberOfParamInState
unsigned int SmolDock::Score::VinaLikeScoringFunction::numberOfParamInState private
Definition at line 95 of file VinaLikeScoringFunction.h.
numberOfRotatableBonds
unsigned int SmolDock::Score::VinaLikeScoringFunction::numberOfRotatableBonds private
Definition at line 96 of file VinaLikeScoringFunction.h.
prot
const iProtein& SmolDock::Score::VinaLikeScoringFunction::prot private
Definition at line 91 of file VinaLikeScoringFunction.h.
startingConformation
iConformer SmolDock::Score::VinaLikeScoringFunction::startingConformation private
Definition at line 90 of file VinaLikeScoringFunction.h.
The documentation for this class was generated from the following files:
VinaLikeScoringFunction.h
VinaLikeScoringFunction.cpp