SmolDock: cli_interface.cpp File Reference
cli_interface.cpp File Reference
#include <iostream>
#include <memory>
#include <string>
#include "Structures/Molecule.h"
#include "Structures/Protein.h"
#include "Engines/PoseRefiner.h"
#include "Structures/InputPostProcessors/VinaCompatibilityPostProcessor.h"
#include "Engines/ConformerRigidDockingEngine.h"
#include <boost/log/core.hpp>
#include <boost/log/trivial.hpp>
#include <boost/log/expressions.hpp>
#include <boost/log/utility/setup/console.hpp>
#include <boost/log/sinks/text_file_backend.hpp>
#include <boost/log/utility/setup/file.hpp>
#include <boost/filesystem.hpp>
#include <boost/program_options.hpp>
#include <Utilities/PDBWriter.h>
Functions
int main (int argc, char *argv[])
Function Documentation
main()
int main (int argc, char * argv[])
Definition at line 47 of file cli_interface.cpp.
References SmolDock::PDBWriter::addLigand(), SmolDock::Engine::AbstractDockingEngine::DockingBoxSetting::center, SmolDock::Engine::AbstractDockingEngine::DockingBoxSetting::centeredAround, SmolDock::Engine::ConformerRigidDockingEngine::getDockingResult(), SmolDock::Heuristics::IteratedLocalSearch, SmolDock::Optimizer::L_BFGS, SmolDock::Molecule::populateFromMol2File(), SmolDock::Molecule::populateFromMolFile(), SmolDock::Protein::populateFromPDB(), SmolDock::Engine::AbstractDockingEngine::DockingBoxSetting::radius, SmolDock::Engine::ConformerRigidDockingEngine::runDockingEngine(), SmolDock::Engine::ConformerRigidDockingEngine::setDockingBox(), SmolDock::Engine::ConformerRigidDockingEngine::setupDockingEngine(), SmolDock::Engine::AbstractDockingEngine::DockingBoxSetting::type, SmolDock::Score::VinaRigid, and SmolDock::PDBWriter::writePDB().