SmolDock: SmolDock Namespace Reference
SmolDock Namespace Reference
Global namespace for SmolDock.
Namespaces
Engine
Docking engines.
Score
Free-standing docking score functions.
Wrapper
Classes
class AminoAcid
class Atom
class Bond
class DockingResult
class DockingResultPrinter
class GradientCalculator
class GradientDescentLineSearch
struct iConformer
struct iGradient
class IntermediateConformerCollector
struct iProtein
Internal, fast representation of Protein for efficiency.
struct iQuaternion
struct iTransform
struct iTranslation
struct iVect
class Molecule
Class representing "rich" molecule.
class PDBWriter
A PDB file writer for ligands.
class Protein
class ReScorer
class Structure
Functions
iQuaternion iQuaternionIdentityInit ()
iTransform iTransformIdentityInit ()
void applyRotationInPlace (iVect &vec, const iQuaternion &qt)
iVect applyRotation (const iVect &v, const iQuaternion &qt)
void applyTranslationInPlace (iVect &v, const iTranslation &t)
iVect applyTranslation (const iVect &v, const iTranslation &t)
void applyTransformInPlace (iVect &v, const iTransform &tr)
iVect applyTransform (const iVect &v, const iTransform &tr)
void applyTransformInPlace (iConformer &conformer, const iTransform &tr)
double quaternionNorm (iQuaternion quat)
double vectorNorm (iVect v)
void normalizeQuaternionInPlace (iQuaternion &quat)
iQuaternion normalizeQuaternion (const iQuaternion &quat)
std::string resTypeToString (AminoAcid::AAType t)
AminoAcid::AAType stringToResType (const std::string &shorthand_or_name)
std::string atomTypeToString (const Atom::AtomType t)
std::string atomTypeToSymbolString (const Atom::AtomType t)
Atom::AtomType stringToAtomType (const std::string &symbol_or_name)
double atomTypeToAtomicRadius (Atom::AtomType t)
void AssignBondOrderFromTemplateSMILES (std::shared_ptr< RDKit::RWMol > mol, const std::string &smiles)
Detailed Description
Global namespace for SmolDock.
Class Documentation
SmolDock::DockingResult
class SmolDock::DockingResult
Definition at line 29 of file DockingResult.h.
Class Members
vector< Molecule > ligandPoses
SmolDock::GradientCalculator
class SmolDock::GradientCalculator
template<typename LigandState, typename LigandTransform>
class SmolDock::GradientCalculator< LigandState, LigandTransform >
Definition at line 11 of file GradientCalculator.h.
SmolDock::iConformer
struct SmolDock::iConformer
Definition at line 30 of file iConformer.h.
Class Members
vector< double > atomicRadius
vector< unsigned char > type
vector< unsigned char > variant
vector< double > x
vector< double > y
vector< double > z
SmolDock::iGradient
struct SmolDock::iGradient
Definition at line 48 of file iTransform.h.
Class Members
double ds
double dt
double du
double dv
double dx
double dy
double dz
SmolDock::iProtein
struct SmolDock::iProtein
Internal, fast representation of Protein for efficiency.
See also
iAtom, iConformer
Definition at line 36 of file iProtein.h.
Class Members
map< unsigned int, tuple< unsigned long, unsigned long > > AAId_to_AtomPositionInVect Map the AAId of residues to the corresponding position of the atoms in the vector.
vector< double > atomicRadius
double center_x Pseudo-center of protein as a mean of each atom coordinate.
double center_y
double center_z
vector< unsigned char > type
vector< unsigned char > variant
vector< double > x
vector< double > y
vector< double > z
SmolDock::iQuaternion
struct SmolDock::iQuaternion
Definition at line 17 of file iTransform.h.
Class Members
double s
double t
double u
double v
SmolDock::iTransform
struct SmolDock::iTransform
Definition at line 31 of file iTransform.h.
Class Members
iQuaternion rota
iTranslation transl
SmolDock::iTranslation
struct SmolDock::iTranslation
Definition at line 27 of file iTransform.h.
Class Members
double x
double y
double z
SmolDock::iVect
struct SmolDock::iVect
Definition at line 23 of file iTransform.h.
Class Members
double x
double y
double z
Function Documentation
applyRotation()
iVect SmolDock::applyRotation (const iVect & v, const iQuaternion & qt) inline
Definition at line 76 of file iTransform.h.
References applyRotationInPlace().
     {
         iVect res(v);
         applyRotationInPlace(res,qt);
         return res;
     }
applyRotationInPlace()
void SmolDock::applyRotationInPlace (iVect & vec, const iQuaternion & qt) inline
Definition at line 65 of file iTransform.h.
References SmolDock::iQuaternion::s, SmolDock::iQuaternion::t, SmolDock::iQuaternion::u, SmolDock::iQuaternion::v, SmolDock::iVect::x, SmolDock::iVect::y, and SmolDock::iVect::z.
     {
         iVect v = vec;
         //TODO : Check this quaternion rotation formula
         //TODO : Refactor this formula to be clearer
         vec.x = qt.s*qt.s*v.x + 2*qt.v*qt.s*v.z - 2*qt.t*qt.s*v.y + qt.u*qt.u*v.x + 2*qt.v*qt.u*v.y + 2*qt.t*qt.u*v.z - qt.t*qt.t*v.x - qt.v*qt.v*v.x;
         vec.y = 2*qt.u*qt.v*v.x + qt.v*qt.v*v.y + 2*qt.t*qt.v*v.z + 2*qt.s*qt.t*v.x - qt.t*qt.t*v.y + qt.s*qt.s*v.y - 2*qt.u*qt.s*v.z - qt.u*qt.u*v.y;
         vec.z = 2*qt.u*qt.t*v.x + 2*qt.v*qt.t*v.y + qt.t*qt.t*v.z - 2*qt.s*qt.v*v.x - qt.v*qt.v*v.z + 2*qt.s*qt.u*v.y - qt.u*qt.u*v.z + qt.s*qt.s*v.z;
     }
applyTransform()
iVect SmolDock::applyTransform (const iVect & v, const iTransform & tr) inline
Definition at line 105 of file iTransform.h.
References applyTransformInPlace().
     {
         iVect res(v);
         applyTransformInPlace(res,tr);
         return res;
     }
applyTransformInPlace() [1/2]
void SmolDock::applyTransformInPlace (iVect & v, const iTransform & tr) inline
Definition at line 99 of file iTransform.h.
References applyRotationInPlace(), applyTranslationInPlace(), SmolDock::iTransform::rota, and SmolDock::iTransform::transl.
     {
         applyRotationInPlace(v,tr.rota);
         applyTranslationInPlace(v,tr.transl);
     }
applyTransformInPlace() [2/2]
void SmolDock::applyTransformInPlace (iConformer & conformer, const iTransform & tr) inline
Definition at line 113 of file iTransform.h.
References applyTransformInPlace(), SmolDock::iVect::x, SmolDock::iConformer::x, SmolDock::iVect::y, SmolDock::iConformer::y, SmolDock::iVect::z, and SmolDock::iConformer::z.
     {
         for (unsigned int i = 0; i < conformer.x.size(); i++) {
             iVect posVect = {conformer.x[i],conformer.y[i],conformer.z[i]};
             applyTransformInPlace(posVect, tr);
             conformer.x[i] = posVect.x;
             conformer.y[i] = posVect.y;
             conformer.z[i] = posVect.z;
         }
     }
applyTranslation()
iVect SmolDock::applyTranslation (const iVect & v, const iTranslation & t) inline
Definition at line 90 of file iTransform.h.
References applyTranslationInPlace().
     {
         iVect res(v);
         applyTranslationInPlace(res,t);
         return res;
     }
applyTranslationInPlace()
void SmolDock::applyTranslationInPlace (iVect & v, const iTranslation & t) inline
Definition at line 83 of file iTransform.h.
References SmolDock::iVect::x, SmolDock::iTranslation::x, SmolDock::iVect::y, SmolDock::iTranslation::y, SmolDock::iVect::z, and SmolDock::iTranslation::z.
     {
         v.x += t.x;
         v.y += t.y;
         v.z += t.z;
     }
AssignBondOrderFromTemplateSMILES()
void SmolDock::AssignBondOrderFromTemplateSMILES (std::shared_ptr< RDKit::RWMol > mol, const std::string & smiles)
Definition at line 11 of file PDBLigandUtils.cpp.
{
         RDKit::RWMol *attempt_ptr = nullptr;
         try {
             /* This can throw */
             attempt_ptr = RDKit::SmilesToMol(smiles);
         }
         catch (...) {
             attempt_ptr = nullptr;
         }
         if (attempt_ptr == nullptr) {
             BOOST_LOG_TRIVIAL(error)
                 << "Error in AssignBondOrderFromTemplateSMILES(std::shared_ptr<RDKit::RWMol> mol,const std::string& smiles)";
             BOOST_LOG_TRIVIAL(error) << "for teplate smiles = " << smiles;
             BOOST_LOG_TRIVIAL(error) << "The SMILES string was not correctly parsed by RDKit.";
             BOOST_LOG_TRIVIAL(error)
                 << "This often indicated a malformed SMILES. (but not always, RDKit has parsing bugs)";
             BOOST_LOG_TRIVIAL(error) << "Non-modified mol will be used (likely with incorrect bond order)";
         }
         std::shared_ptr<RDKit::RWMol> templatemol(attempt_ptr);
         RDKit::MolOps::removeHs(*(mol));
         // The following code, until the END RDKIT CODE comment, is a C++ translation
         // of python code from RDKit, in particular, the function AssignBondOrdersFromTemplate
         //
         // As a reminder, the copyright for this code is
         //  Copyright (C) 2001-2017 Greg Landrum and Rational Discovery LLC
         //
         //   @@ All Rights Reserved @@
         //  The contents are covered by the terms of the BSD license
         //  which is included in the file COPYING
         //
         // RDKit::MatchVectType matches = std::vector<std::pair<int, int>>
         //  The format is (queryAtomIdx, molAtomIdx)
         RDKit::MatchVectType matches;
         bool matching = RDKit::SubstructMatch((RDKit::ROMol) *mol, (RDKit::ROMol) *templatemol, matches);
         if (!matching) {
             // We make a copy on which we will remove all double bond/charges/... to compare
             std::shared_ptr<RDKit::RWMol> templatemol_plainstruct(new RDKit::RWMol(*templatemol));
             // Set all bonds to single, non-aromatic
             for (int i = 0; i < mol->getNumBonds(); i++) {
                 auto bond = mol->getBondWithIdx(i);
                 bond->setIsAromatic(false);
                 bond->setBondType(RDKit::Bond::BondType::SINGLE);
             }
             // Also in templatemol_plainstruct
             for (int i = 0; i < templatemol_plainstruct->getNumBonds(); i++) {
                 auto bond = templatemol_plainstruct->getBondWithIdx(i);
                 bond->setIsAromatic(false);
                 bond->setBondType(RDKit::Bond::BondType::SINGLE);
             }
             // Remove all charges
             for (int i = 0; i < mol->getNumAtoms(); i++) {
                 auto atom = mol->getAtomWithIdx(i);
                 atom->setFormalCharge(0);
             }
             for (int i = 0; i < templatemol_plainstruct->getNumAtoms(); i++) {
                 auto atom = templatemol_plainstruct->getAtomWithIdx(i);
                 atom->setFormalCharge(0);
             }
             bool matching = RDKit::SubstructMatch((RDKit::ROMol) *mol, (RDKit::ROMol) *templatemol_plainstruct, matches);
             if (!matching) // Cant reconcile even without charges or double bond
             {
                 BOOST_LOG_TRIVIAL(error)
                     << "Cannot match molecule with SMILES template, thus cannot adjust bond order ";
                 BOOST_LOG_TRIVIAL(error) << "Plain mol will be used (all bond order single, no charges, no nothing)";
                 return;
             }
         }
         // After this point, we are matching (or we returned)
         // And we have matches in RDKit::MatchVectType matches
         // For each bond of the template, we find the corresponding one in the molecule to edit
         // Then we set it to the same characteristics
         for (int i = 0; i < templatemol->getNumBonds(); i++) {
             auto template_bond = templatemol->getBondWithIdx(i);
             // RDKit::MatchVectType matches = std::vector<std::pair<int, int>>
             //  The format is (queryAtomIdx, molAtomIdx)
             // So we find_if for matching queryAtomIdx to the beginning and end of the bond
             int idx_atom1 = std::get<1>(*(std::find_if(matches.begin(), matches.end(),
                                                        [&](const std::pair<int, int> &e) {
                                                            return (std::get<0>(e) == template_bond->getBeginAtomIdx());
                                                        })));
             int idx_atom2 = std::get<1>(*(std::find_if(matches.begin(), matches.end(),
                                                        [&](const std::pair<int, int> &e) {
                                                            return (std::get<0>(e) == template_bond->getEndAtomIdx());
                                                        })));
             auto bond_to_edit = mol->getBondBetweenAtoms(idx_atom1, idx_atom2);
             bond_to_edit->setBondType(template_bond->getBondType());
             bond_to_edit->setIsAromatic(template_bond->getIsAromatic());
         }
         for (int i = 0; i < templatemol->getNumAtoms(); i++) {
             auto template_atom = templatemol->getAtomWithIdx(i);
             int idx_atom_to_edit = std::get<1>(*(std::find_if(matches.begin(), matches.end(),
                                                               [&](const std::pair<int, int> &e) {
                                                                   return (std::get<0>(e) == i);
                                                               })));
             auto atom_to_edit = mol->getAtomWithIdx(idx_atom_to_edit);
             atom_to_edit->setHybridization(template_atom->getHybridization());
             atom_to_edit->setIsAromatic(template_atom->getIsAromatic());
             atom_to_edit->setNumExplicitHs(template_atom->getNumExplicitHs());
             atom_to_edit->setFormalCharge(template_atom->getFormalCharge());
             atom_to_edit->setChiralTag(template_atom->getChiralTag());
         }
         RDKit::MolOps::sanitizeMol(*mol);
         // //////////////// END RDKIT CODE  //////////////////////////////////
     }
atomTypeToAtomicRadius()
double SmolDock::atomTypeToAtomicRadius (Atom::AtomType t)
Definition at line 86 of file Atom.cpp.
References SmolDock::Atom::AtomTypeLabel.
{
         auto it = std::find_if(Atom::AtomTypeLabel.begin(), Atom::AtomTypeLabel.end(),
                                [&](const std::tuple<Atom::AtomType, std::string, std::string, double> &e) {
                                    return std::get<0>(e) == t;
                                });
         if (it != Atom::AtomTypeLabel.end()) {
             return std::get<3>(*it);
         }else{
             BOOST_LOG_TRIVIAL(error) << "Encountered unknown AtomType while finding atomic radius: " << static_cast<unsigned char>(t);
             return 0;
         }
     }
atomTypeToString()
std::string SmolDock::atomTypeToString (const Atom::AtomType t)
Definition at line 47 of file Atom.cpp.
References SmolDock::Atom::AtomTypeLabel.
{
         auto it = std::find_if(Atom::AtomTypeLabel.begin(), Atom::AtomTypeLabel.end(),
                                [&](const std::tuple<Atom::AtomType, std::string, std::string, double> &e) {
                                    return std::get<0>(e) == t;
                                });
         if (it != Atom::AtomTypeLabel.end()) {
             return std::get<1>(*it);
         }else{
             BOOST_LOG_TRIVIAL(error) << "Encountered unknown atom AtomType while converting to string: " << static_cast<unsigned char>(t);
             return std::string("");
         }
     }
atomTypeToSymbolString()
std::string SmolDock::atomTypeToSymbolString (const Atom::AtomType t)
Definition at line 60 of file Atom.cpp.
References SmolDock::Atom::AtomTypeLabel.
{
         auto it = std::find_if(Atom::AtomTypeLabel.begin(), Atom::AtomTypeLabel.end(),
                                [&](const std::tuple<Atom::AtomType, std::string, std::string, double> &e) {
                                    return std::get<0>(e) == t;
                                });
         if (it != Atom::AtomTypeLabel.end()) {
             return std::get<2>(*it);
         }else{
             BOOST_LOG_TRIVIAL(error) << "Encountered unknown atom AtomType while converting to symbol string: " << static_cast<unsigned char>(t);
             return std::string("");
         }
     }
iQuaternionIdentityInit()
iQuaternion SmolDock::iQuaternionIdentityInit () inline
Definition at line 38 of file iTransform.h.
References SmolDock::iQuaternion::s, SmolDock::iQuaternion::t, SmolDock::iQuaternion::u, and SmolDock::iQuaternion::v.
     {
         iQuaternion qt;
         qt.s = 0.5;
         qt.u = 0.5;
         qt.v = 0.5;
         qt.t = 0.5;
         return qt;
     }
iTransformIdentityInit()
iTransform SmolDock::iTransformIdentityInit () inline
Definition at line 55 of file iTransform.h.
References iQuaternionIdentityInit(), SmolDock::iTransform::rota, SmolDock::iTransform::transl, SmolDock::iTranslation::x, SmolDock::iTranslation::y, and SmolDock::iTranslation::z.
     {
         iTransform tr;
         tr.transl.x = 0.0;
         tr.transl.y = 0.0;
         tr.transl.z = 0.0;
         tr.rota = iQuaternionIdentityInit();
         return tr;
     }
normalizeQuaternion()
iQuaternion SmolDock::normalizeQuaternion (const iQuaternion & quat) inline
Definition at line 147 of file iTransform.h.
References normalizeQuaternionInPlace().
     {
         iQuaternion ret = quat;
         normalizeQuaternionInPlace(ret);
         return ret;
     }
normalizeQuaternionInPlace()
void SmolDock::normalizeQuaternionInPlace (iQuaternion & quat) inline
Definition at line 138 of file iTransform.h.
References quaternionNorm(), SmolDock::iQuaternion::s, SmolDock::iQuaternion::t, SmolDock::iQuaternion::u, and SmolDock::iQuaternion::v.
     {
         double norm = quaternionNorm(quat);
         quat.s /= norm;
         quat.u /= norm;
         quat.v /= norm;
         quat.t /= norm;
     }
quaternionNorm()
double SmolDock::quaternionNorm (iQuaternion quat) inline
Definition at line 124 of file iTransform.h.
References SmolDock::iQuaternion::s, SmolDock::iQuaternion::t, SmolDock::iQuaternion::u, and SmolDock::iQuaternion::v.
     {
         return std::sqrt(
                 std::pow(quat.s,2) + std::pow(quat.u,2) + std::pow(quat.v,2) + std::pow(quat.t,2)
                 );
     }
resTypeToString()
std::string SmolDock::resTypeToString (AminoAcid::AAType t)
Definition at line 65 of file AminoAcid.cpp.
References SmolDock::AminoAcid::AAShorthandSet.
{
         auto it = std::find_if(AminoAcid::AAShorthandSet.begin(), AminoAcid::AAShorthandSet.end(),
                                [&](const std::tuple<AminoAcid::AAType, std::string, std::string> &e) {
                                    return std::get<0>(e) == t;
                                });
         if (it != AminoAcid::AAShorthandSet.end()) {
             return std::get<1>(*it);
         }else{
             return "";
         }
     }
stringToAtomType()
Atom::AtomType SmolDock::stringToAtomType (const std::string & symbol_or_name)
Definition at line 73 of file Atom.cpp.
References SmolDock::Atom::AtomTypeLabel, and SmolDock::Atom::unknown.
{
         auto it = std::find_if(Atom::AtomTypeLabel.begin(), Atom::AtomTypeLabel.end(),
                                [&](const std::tuple<Atom::AtomType, std::string, std::string, double> &e) {
                                    return (std::get<1>(e) == symbol_or_name) || (std::get<2>(e) == symbol_or_name);
                                });
         if (it != Atom::AtomTypeLabel.end()) {
             return std::get<0>(*it);
         } else {
             BOOST_LOG_TRIVIAL(error) << "Encountered unknown atom symbol_or_name while converting from string: " << symbol_or_name;
             return Atom::AtomType::unknown;
         }
     }
stringToResType()
AminoAcid::AAType SmolDock::stringToResType (const std::string & shorthand_or_name)
Definition at line 77 of file AminoAcid.cpp.
References SmolDock::AminoAcid::AAShorthandSet.
{
         auto it = std::find_if(AminoAcid::AAShorthandSet.begin(), AminoAcid::AAShorthandSet.end(),
                                [&](const std::tuple<AminoAcid::AAType, std::string, std::string> &e) {
                                    return (std::get<1>(e) == shorthand_or_name) ||
                                           (std::get<2>(e) == shorthand_or_name);
                                });
         if (it != AminoAcid::AAShorthandSet.end()) {
             return std::get<0>(*it);
         } else {
 #ifdef SMOLDOCK_VERBOSE_DEBUG
             std::cout << "[!] Encountered unknown residue shorthand_or_name : " << shorthand_or_name << std::endl;
 #endif
             return AminoAcid::AminoAcid::AAType::unknown;
         }
     }
vectorNorm()
double SmolDock::vectorNorm (iVect v) inline
Definition at line 131 of file iTransform.h.
References SmolDock::iVect::x, SmolDock::iVect::y, and SmolDock::iVect::z.
     {
         return std::sqrt(
                 std::pow(v.x,2) + std::pow(v.y,2) + std::pow(v.z,2)
         );
     }