SmolDock: SmolDock::Score Namespace Reference
SmolDock::Score Namespace Reference
Free-standing docking score functions.
Classes
class ScoringFunction
The inferface specification for ScoringFunction object.
class VinaLikeRigidScoringFunction
class VinaLikeScoringFunction
Enumerations
enum ScoringFunctionType { ScoringFunctionType::VinaRigid, ScoringFunctionType::Vina }
Functions
std::shared_ptr< ScoringFunction > scoringFunctionFactory (ScoringFunctionType t, const iConformer &conformer, const iProtein &protein, const iTransform &transform, double differential_upsilon)
bool isHydrophobic (unsigned char atomicNumber, unsigned int variantFlags)
bool isHydrogenAcceptor (unsigned char atomicNumber, unsigned int atomVariantFlags)
bool isHydrogenDonor (unsigned char atomicNumber, unsigned int atomVariantFlags)
bool hydrogenDonorAcceptorPair (unsigned char atomicNumber1, unsigned int atom1VariantFlags, unsigned char atomicNumber2, unsigned int atom2VariantFlags)
bool hydrogenBondingPossible (unsigned char atomicNumber1, unsigned int atom1VariantFlags, unsigned char atomicNumber2, unsigned int atom2VariantFlags)
double scoreForAtomCouple (double distance, unsigned char atom1AtomicNumber, unsigned int atom1AtomVariant, unsigned char atom2AtomicNumber, unsigned int atom2AtomVariant)
double vina_like_rigid_inter_scoring_func (const iConformer &conformer, const iTransform &transform, const iProtein &protein)
Compute inter-molecular part of the docking score, according to the Vina scoring function.
double VinaLikeIntermolecularScoringFunction (const iConformer &ligand_, const iTransform &transform, const iProtein &protein)
Detailed Description
Free-standing docking score functions.
Enumeration Type Documentation
ScoringFunctionType
enum SmolDock::Score::ScoringFunctionType strong
Enumerator
VinaRigid
Vina
Definition at line 17 of file ScoringFunctionFactory.h.
Function Documentation
hydrogenBondingPossible()
bool SmolDock::Score::hydrogenBondingPossible (unsigned char atomicNumber1, unsigned int atom1VariantFlags, unsigned char atomicNumber2, unsigned int atom2VariantFlags) inline
Definition at line 51 of file VinaLikeCommon.h.
References hydrogenDonorAcceptorPair().
hydrogenDonorAcceptorPair()
bool SmolDock::Score::hydrogenDonorAcceptorPair (unsigned char atomicNumber1, unsigned int atom1VariantFlags, unsigned char atomicNumber2, unsigned int atom2VariantFlags) inline
Definition at line 45 of file VinaLikeCommon.h.
References isHydrogenAcceptor(), and isHydrogenDonor().
isHydrogenAcceptor()
bool SmolDock::Score::isHydrogenAcceptor (unsigned char atomicNumber, unsigned int atomVariantFlags) inline
Definition at line 33 of file VinaLikeCommon.h.
References SmolDock::Atom::hydrogenAcceptor.
isHydrogenDonor()
bool SmolDock::Score::isHydrogenDonor (unsigned char atomicNumber, unsigned int atomVariantFlags) inline
Definition at line 39 of file VinaLikeCommon.h.
References SmolDock::Atom::hydrogenDonor.
isHydrophobic()
bool SmolDock::Score::isHydrophobic (unsigned char atomicNumber, unsigned int variantFlags) inline
Definition at line 24 of file VinaLikeCommon.h.
References SmolDock::Atom::apolar.
scoreForAtomCouple()
double SmolDock::Score::scoreForAtomCouple (double distance, unsigned char atom1AtomicNumber, unsigned int atom1AtomVariant, unsigned char atom2AtomicNumber, unsigned int atom2AtomVariant) inline
Definition at line 70 of file VinaLikeCommon.h.
References hydrogenBondingPossible(), and isHydrophobic().
scoringFunctionFactory()
std::shared_ptr< ScoringFunction > SmolDock::Score::scoringFunctionFactory (ScoringFunctionType t, const iConformer & conformer, const iProtein & protein, const iTransform & transform, double differential_upsilon)
Definition at line 12 of file ScoringFunctionFactory.cpp.
References Vina, and VinaRigid.
vina_like_rigid_inter_scoring_func()
double SmolDock::Score::vina_like_rigid_inter_scoring_func (const iConformer & conformer, const iTransform & transform, const iProtein & protein)
Compute inter-molecular part of the docking score, according to the Vina scoring function.
The transform provided will be applied to the entire, rigid ligand.
Parameters
conformer Ligand conformation & position to evaluate
transform Transformation to apply to the ligand
protein Protein conformation to evaluate
Returns
The docking score
See also
Definition at line 40 of file VinaLikeRigidScoringFunction.cpp.
References SmolDock::applyRigidTransformInPlace(), SmolDock::iProtein::atomicRadius, SmolDock::iConformer::atomicRadius, SmolDock::iProtein::center_x, SmolDock::iProtein::center_y, SmolDock::iProtein::center_z, SmolDock::iConformer::num_rotatable_bond, SmolDock::iProtein::radius, SmolDock::iTransform::rota, scoreForAtomCouple(), SmolDock::iProtein::type, SmolDock::iConformer::type, SmolDock::iProtein::variant, SmolDock::iConformer::variant, SmolDock::iProtein::x, SmolDock::iConformer::x, SmolDock::iProtein::y, SmolDock::iConformer::y, SmolDock::iProtein::z, and SmolDock::iConformer::z.
VinaLikeIntermolecularScoringFunction()
double SmolDock::Score::VinaLikeIntermolecularScoringFunction (const iConformer & ligand_, const iTransform & transform, const iProtein & protein)
Definition at line 20 of file VinaLikeScoringFunction.cpp.
References SmolDock::applyBondRotationInPlace(), SmolDock::applyRigidTransformInPlace(), SmolDock::iProtein::atomicRadius, SmolDock::iConformer::atomicRadius, SmolDock::iTransform::bondRotationsAngles, SmolDock::iProtein::center_x, SmolDock::iProtein::center_y, SmolDock::iProtein::center_z, SmolDock::iConformer::num_rotatable_bond, SmolDock::iProtein::radius, SmolDock::iTransform::rota, scoreForAtomCouple(), SmolDock::iProtein::type, SmolDock::iConformer::type, SmolDock::iProtein::variant, SmolDock::iConformer::variant, SmolDock::iProtein::x, SmolDock::iConformer::x, SmolDock::iProtein::y, SmolDock::iConformer::y, SmolDock::iProtein::z, and SmolDock::iConformer::z.