SmolDock: vina_refiner.cpp File Reference
vina_refiner.cpp File Reference
#include <iostream>
#include <memory>
#include <string>
#include "Structures/Molecule.h"
#include "Structures/Protein.h"
#include "Engines/PoseRefiner.h"
#include "Structures/InputPostProcessors/VinaCompatibilityPostProcessor.h"
#include <boost/log/core.hpp>
#include <boost/log/trivial.hpp>
#include <boost/log/expressions.hpp>
#include <boost/log/utility/setup/console.hpp>
#include <boost/log/sinks/text_file_backend.hpp>
#include <boost/log/utility/setup/file.hpp>
#include <boost/filesystem.hpp>
#include <boost/program_options.hpp>
#include <Utilities/PDBWriter.h>
Functions
int main (int argc, char *argv[])
Function Documentation
main()
int main (int argc, char * argv[])
Definition at line 45 of file vina_refiner.cpp.
References SmolDock::PDBWriter::addLigand(), SmolDock::Engine::PoseRefiner::applyToLigand(), SmolDock::Engine::PoseRefiner::getFinalScore(), SmolDock::Engine::PoseRefiner::getInitialScore(), SmolDock::Engine::PoseRefiner::getScoreDifference(), SmolDock::Optimizer::L_BFGS, SmolDock::Protein::populateFromPDB(), SmolDock::Engine::PoseRefiner::refinePose(), SmolDock::Score::VinaRigid, and SmolDock::PDBWriter::writePDB().